package proxy

import (
	"bufio"
	"bytes"
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"regexp"
	"strconv"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/klxhunter/agent-rate-limit/api-gateway/config"
	"github.com/klxhunter/agent-rate-limit/api-gateway/metrics"
	"github.com/klxhunter/agent-rate-limit/api-gateway/privacy"
	"github.com/klxhunter/agent-rate-limit/api-gateway/privacy/masking"
	"github.com/klxhunter/agent-rate-limit/api-gateway/tokenizer"
)

const maxSSELineSize = 8 * 1024 * 1024 // 8MB - covers large base64 images in Z.AI built-in tool results

// xmlBlockRe matches any XML-like block generated by GLM models.
var (
	xmlBlockRe     = regexp.MustCompile(`(?si)<(?:tool_call|tool_response|tool_use|tool_result|directive|system|thinking|action|execute)(?:>|\s).*?</(?:tool_call|tool_response|tool_use|tool_result|directive|system|thinking|action|execute)>?\s*`)
	toolUseBlockRe = xmlBlockRe

	xmlTagPrefixes = []string{
		"<tool_call", "<tool_response", "<tool_use", "<tool_result",
		"<directive", "<system", "<thinking", "<action", "<execute",

		// HTML tags that need buffering for cross-chunk conversion.
		"<details", "<summary",
	}

	// htmlDetailTagRe converts GLM <details><summary> HTML to markdown.
	htmlDetailTagRe  = regexp.MustCompile(`</?details[^>]*>`)
	htmlSummaryTagRe = regexp.MustCompile(`<summary>(.*?)</summary>`)

	thaiCharRe = regexp.MustCompile(`[\x{0E00}-\x{0E7F}]`)
)

// toolUseStripper buffers streaming text and strips XML blocks
// that GLM models emit as plain text, spanning multiple SSE chunks.
type toolUseStripper struct {
	buf strings.Builder
}

func partialTagEnd(s string) int {
	for _, prefix := range xmlTagPrefixes {
		for i := 1; i <= len(prefix); i++ {
			if len(s) < i {
				break
			}
			tail := s[len(s)-i:]
			if tail[0] == '<' && strings.HasPrefix(prefix, tail) {
				return len(s) - i
			}
		}
	}
	return -1
}

func hasOpenTag(s string) bool {
	for _, prefix := range xmlTagPrefixes {
		if idx := strings.LastIndex(s, prefix); idx >= 0 {
			after := s[idx+len(prefix):]
			closeTag := "</" + prefix[1:]
			if strings.Contains(after, ">") && !strings.Contains(s[idx:], closeTag) {
				return true
			}
		}
	}
	return false
}

func (s *toolUseStripper) Feed(text string) string {
	// Fast path: skip regex entirely when no '<' and buffer is empty
	if s.buf.Len() == 0 && !strings.Contains(text, "<") {
		return text
	}
	s.buf.WriteString(text)
	content := s.buf.String()

	// Check for open tags BEFORE applying HTML regexes that would remove them.
	// This ensures <details>/<summary> are buffered across chunks.
	if hasOpenTag(content) {
		clean := xmlBlockRe.ReplaceAllString(content, "")
		for _, prefix := range xmlTagPrefixes {
			if idx := strings.LastIndex(clean, prefix); idx >= 0 {
				s.buf.Reset()
				s.buf.WriteString(clean[idx:])
				clean = clean[:idx]
				return clean
			}
		}
	}
	if idx := partialTagEnd(content); idx >= 0 {
		clean := xmlBlockRe.ReplaceAllString(content, "")
		s.buf.Reset()
		s.buf.WriteString(clean[idx:])
		return clean[:idx]
	}

	// All tags are complete - apply full conversion.
	clean := xmlBlockRe.ReplaceAllString(content, "")
	clean = htmlDetailTagRe.ReplaceAllString(clean, "")
	clean = htmlSummaryTagRe.ReplaceAllString(clean, "**$1**\n")
	s.buf.Reset()
	return clean
}

func (s *toolUseStripper) Flush() string {
	content := s.buf.String()
	s.buf.Reset()
	content = xmlBlockRe.ReplaceAllString(content, "")
	content = htmlDetailTagRe.ReplaceAllString(content, "")
	content = htmlSummaryTagRe.ReplaceAllString(content, "**$1**\n")
	for _, prefix := range xmlTagPrefixes {
		if idx := strings.LastIndex(content, prefix); idx >= 0 {
			content = content[:idx]
		}
	}
	return content
}

// allowedResponseHeaders lists headers safe to pass from upstream to client.
var allowedResponseHeaders = map[string]bool{
	"Content-Type":                                     true,
	"X-RateLimit-Limit":                                true,
	"X-RateLimit-Remaining":                            true,
	"X-RateLimit-Reset":                                true,
	"Retry-After":                                      true,
	"Request-Id":                                       true,
	"Anthropic-Ratelimit-Requests-Remaining":           true,
	"Anthropic-Ratelimit-Tokens-Remaining":             true,
	"Anthropic-Ratelimit-Unified-Status":               true,
	"Anthropic-Ratelimit-Unified-5h-Status":            true,
	"Anthropic-Ratelimit-Unified-5h-Utilization":       true,
	"Anthropic-Ratelimit-Unified-5h-Reset":             true,
	"Anthropic-Ratelimit-Unified-7d-Status":            true,
	"Anthropic-Ratelimit-Unified-7d-Utilization":       true,
	"Anthropic-Ratelimit-Unified-7d-Reset":             true,
	"Anthropic-Ratelimit-Unified-Fallback-Percentage":  true,
	"Anthropic-Ratelimit-Unified-Fallback":             true,
	"Anthropic-Ratelimit-Unified-Reset":                true,
	"Anthropic-Ratelimit-Unified-Representative-Claim": true,
	"X-Ratelimit-Limit-Requests":                       true,
	"X-Ratelimit-Limit-Tokens":                         true,
	"X-Ratelimit-Remaining-Requests":                   true,
	"X-Ratelimit-Remaining-Tokens":                     true,
	"X-Ratelimit-Reset-Requests":                       true,
	"X-Ratelimit-Reset-Tokens":                         true,
}

// stripUnsupportedBetas removes beta flags unsupported by the model from the anthropic-beta header.
func stripUnsupportedBetas(h *http.Header, model string) {
	beta := h.Get("anthropic-beta")
	if beta == "" {
		return
	}
	strip := false
	if strings.Contains(model, "haiku") || strings.Contains(model, "3-5-sonnet") {
		strip = true
	}
	if !strip {
		return
	}
	parts := strings.Split(beta, ",")
	var kept []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if strings.HasPrefix(p, "effort-") || strings.HasPrefix(p, "interleaved-thinking-") {
			continue
		}
		kept = append(kept, p)
	}
	h.Set("anthropic-beta", strings.Join(kept, ","))
}

// FeedbackFunc is called by the proxy after each upstream attempt.
// Defined here to avoid import cycles.
type FeedbackFunc func(statusCode int, rtt time.Duration, headers http.Header)

// Error response format matching Anthropic API.

type ErrorResponse struct {
	Type  string      `json:"type"`
	Error ErrorDetail `json:"error"`
}

type ErrorDetail struct {
	Type    string `json:"type"`
	Message string `json:"message"`
}

// AnthropicProxy handles transparent proxying to the Anthropic-compatible upstream.
type AnthropicProxy struct {
	cfg     *config.Config
	client  *http.Client
	metrics *metrics.Metrics
}

// NewAnthropicProxy creates a proxy with optimized HTTP client for upstream calls.
func NewAnthropicProxy(cfg *config.Config, m *metrics.Metrics) *AnthropicProxy {
	return &AnthropicProxy{
		cfg:     cfg,
		client:  SharedClient(0),
		metrics: m,
	}
}

// HasImageContent checks if the LAST user message contains image blocks.
// Only checks the most recent user turn to avoid re-routing to vision model
// when images exist in older conversation history but the current turn is text-only.
func HasImageContent(payload map[string]any) bool {
	msgs, ok := payload["messages"].([]any)
	if !ok {
		return false
	}
	// Find the last user message.
	var lastUserContent any
	for i := len(msgs) - 1; i >= 0; i-- {
		m, ok := msgs[i].(map[string]any)
		if !ok {
			continue
		}
		if role, _ := m["role"].(string); role == "user" {
			lastUserContent = m["content"]
			break
		}
	}
	if lastUserContent == nil {
		return false
	}
	content, ok := lastUserContent.([]any)
	if !ok {
		return false
	}
	for _, block := range content {
		cb, ok := block.(map[string]any)
		if !ok {
			continue
		}
		if t, _ := cb["type"].(string); t == "image" || t == "image_url" {
			return true
		}
	}
	return false
}

// AnthropicToOpenAI converts an Anthropic Messages API payload to OpenAI Chat Completions format.
// Z.AI vision API only accepts "user" and "assistant" roles, so system prompts are prepended
// to the first user message.
func AnthropicToOpenAI(body []byte, model string, m *metrics.Metrics, toolMode string) (map[string]any, error) {
	var src map[string]any
	if err := json.Unmarshal(body, &src); err != nil {
		return nil, err
	}

	// Extract system text before converting messages.
	var systemText string
	if sys, ok := src["system"]; ok {
		switch v := sys.(type) {
		case string:
			systemText = v
		case []any:
			var parts []string
			for _, s := range v {
				if sm, ok := s.(map[string]any); ok {
					if t, _ := sm["text"].(string); t != "" {
						parts = append(parts, t)
					}
				}
			}
			systemText = strings.Join(parts, "\n\n")
		}
	}

	// Supported content types for Z.AI vision API.
	supportedTypes := map[string]bool{
		"text":      true,
		"image":     true,
		"image_url": true,
	}

	// Convert messages.
	srcMsgs, _ := src["messages"].([]any)
	var messages []map[string]any
	for _, msg := range srcMsgs {
		msgMap, ok := msg.(map[string]any)
		if !ok {
			continue
		}
		role, _ := msgMap["role"].(string)

		if toolMode == "native" {
			converted := convertMessageWithTools(msgMap, role)
			messages = append(messages, converted...)
			continue
		}

		// Non-tools path: only user and assistant roles, filter unsupported content types.
		if role != "user" && role != "assistant" {
			continue
		}

		content := msgMap["content"]

		switch v := content.(type) {
		case string:
			messages = append(messages, map[string]any{"role": role, "content": v})
		case []any:
			var parts []map[string]any
			for _, block := range v {
				cb, ok := block.(map[string]any)
				if !ok {
					continue
				}
				t, _ := cb["type"].(string)

				// Filter unsupported content types.
				if !supportedTypes[t] {
					continue
				}

				switch t {
				case "text":
					parts = append(parts, map[string]any{"type": "text", "text": cb["text"]})
				case "image":
					parts = append(parts, convertImageBlock(cb))
				case "image_url":
					parts = append(parts, cb)
				}
			}
			if len(parts) > 0 {
				messages = append(messages, map[string]any{"role": role, "content": parts})
			}
		default:
			messages = append(messages, map[string]any{"role": role, "content": content})
		}
	}

	// Handle system prompt based on tool mode.
	if systemText != "" && len(messages) > 0 {
		// Optimize system text: whitespace cleanup + dedup to save tokens.
		optText, wsSaved := tokenizer.OptimizeWhitespace(systemText)
		dedupText, dedupSaved := tokenizer.DeduplicateSentences(optText)
		if wsSaved > 0 || dedupSaved > 0 {
			slog.Debug("system prompt optimized", "ws_saved", wsSaved, "dedup_saved", dedupSaved, "original_chars", len(systemText), "optimized_chars", len(dedupText))
		}
		if m != nil {
			m.RecordOptimization("whitespace", wsSaved, "input")
			m.RecordOptimization("dedup", dedupSaved, "input")
		}
		systemText = dedupText

		if toolMode == "native" {
			// OpenAI-compatible providers support system role - use it directly
			// so the model properly understands working directory and context.
			toolHint := "\n\nYou have access to tools. Use Write for creating files, Bash for commands, Read for reading files, Edit for editing files. Do NOT run pwd or ls to check the directory - trust the working directory shown above."
			sysMsg := map[string]any{"role": "system", "content": systemText + toolHint}
			messages = append([]map[string]any{sysMsg}, messages...)
		} else {
			// Z.AI mode: prepend to first user message.
			first := messages[0]
			if first["role"] == "user" {
				switch v := first["content"].(type) {
				case string:
					first["content"] = systemText + "\n\n" + v
				case []any:
					sysBlock := map[string]any{"type": "text", "text": systemText}
					newParts := make([]any, 0, len(v)+1)
					newParts = append(newParts, sysBlock)
					for _, p := range v {
						newParts = append(newParts, p)
					}
					first["content"] = newParts
				}
			}
		}
	}

	// Detect Thai in user messages and append language hint.
	thaiRe := thaiCharRe
	hasThai := false
	for _, m := range messages {
		if m["role"] != "user" {
			continue
		}
		switch c := m["content"].(type) {
		case string:
			if thaiRe.MatchString(c) {
				hasThai = true
			}
		case []map[string]any:
			for _, p := range c {
				if t, ok := p["text"].(string); ok && thaiRe.MatchString(t) {
					hasThai = true
				}
			}
		}
	}
	if hasThai && len(messages) > 0 {
		first := messages[0]
		hint := "IMPORTANT: You MUST respond in the same language as the user. If the user writes in Thai, respond in Thai."
		switch v := first["content"].(type) {
		case string:
			first["content"] = hint + "\n\n" + v
		case []any:
			newParts := make([]any, 0, len(v)+1)
			newParts = append(newParts, map[string]any{"type": "text", "text": hint})
			for _, p := range v {
				newParts = append(newParts, p)
			}
			first["content"] = newParts
		}
	}

	result := map[string]any{
		"model":    model,
		"messages": messages,
	}

	// Tool handling based on mode.
	if toolMode == "native" {
		// Native OpenAI function calling format.
		if tools, ok := src["tools"].([]any); ok && len(tools) > 0 {
			var openaiTools []map[string]any
			for _, t := range tools {
				tm, ok := t.(map[string]any)
				if !ok {
					continue
				}
				name, _ := tm["name"].(string)
				desc, _ := tm["description"].(string)
				schema := tm["input_schema"]
				openaiTools = append(openaiTools, map[string]any{
					"type": "function",
					"function": map[string]any{
						"name":        name,
						"description": desc,
						"parameters":  schema,
					},
				})
			}
			if len(openaiTools) > 0 {
				result["tools"] = openaiTools
			}
		}
		if tc, ok := src["tool_choice"]; ok {
			result["tool_choice"] = convertToolChoiceToOpenAI(tc)
		} else if toolMode == "native" {
			if _, hasTools := result["tools"]; hasTools {
				result["tool_choice"] = "auto"
			}
		}
	}
	// Cap max_tokens for Z.AI vision models (max output ~4096).
	const maxVisionTokens = 128000
	if mt, ok := src["max_tokens"]; ok {
		if v, ok := mt.(float64); ok && v > maxVisionTokens {
			result["max_tokens"] = maxVisionTokens
		} else {
			result["max_tokens"] = mt
		}
	} else {
		result["max_tokens"] = maxVisionTokens
	}
	if stream, ok := src["stream"].(bool); ok {
		result["stream"] = stream
		// Z.AI does not support stream_options (error 1210).
		if stream && !strings.HasPrefix(model, "glm-") {
			result["stream_options"] = map[string]any{"include_usage": true}
		}
	}

	return result, nil
}

// convertImageBlock converts Anthropic image to Zhipu image_url format.
// Z.AI vision API only supports base64-encoded images, not external URLs.
// URL images are downloaded and converted to base64 data URIs.
func convertImageBlock(cb map[string]any) map[string]any {
	src, ok := cb["source"].(map[string]any)
	if !ok {
		return cb
	}
	srcType, _ := src["type"].(string)
	var url string
	switch srcType {
	case "base64":
		mediaType, _ := src["media_type"].(string)
		data, _ := src["data"].(string)
		url = fmt.Sprintf("data:%s;base64,%s", mediaType, data)
	case "url":
		imgURL, _ := src["url"].(string)
		if base64URI := FetchImageAsBase64(imgURL); base64URI != "" {
			url = base64URI
		} else {
			// Z.AI vision API doesn't support external URLs - skip this image.
			slog.Warn("skipping URL image that couldn't be fetched for base64 conversion", "url", imgURL)
			return map[string]any{"type": "text", "text": "[image could not be loaded]"}
		}
	}
	return map[string]any{"type": "image_url", "image_url": map[string]any{"url": url}}
}

// CountImageBlocks counts the number of image content blocks in a payload.
func CountImageBlocks(payload map[string]any) int {
	msgs, ok := payload["messages"].([]any)
	if !ok {
		return 0
	}
	count := 0
	for _, msg := range msgs {
		mm, ok := msg.(map[string]any)
		if !ok {
			continue
		}
		blocks, ok := mm["content"].([]any)
		if !ok {
			continue
		}
		for _, block := range blocks {
			cb, ok := block.(map[string]any)
			if !ok {
				continue
			}
			if cb["type"] == "image" {
				count++
			}
		}
	}
	return count
}

// FetchImageAsBase64 downloads an image URL and converts it to a base64 data URI.
func FetchImageAsBase64(imgURL string) string {
	resp, err := imageClient.Get(imgURL)
	if err != nil {
		slog.Warn("failed to fetch image URL for base64 conversion", "url", imgURL, "error", err)
		return ""
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 || resp.ContentLength > 20*1024*1024 {
		slog.Warn("image URL fetch failed or too large", "url", imgURL, "status", resp.StatusCode, "size", resp.ContentLength)
		return ""
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, 20*1024*1024))
	if err != nil {
		slog.Warn("failed to read image data", "url", imgURL, "error", err)
		return ""
	}

	contentType := resp.Header.Get("Content-Type")
	if contentType == "" {
		contentType = http.DetectContentType(data)
	}

	return fmt.Sprintf("data:%s;base64,%s", contentType, base64.StdEncoding.EncodeToString(data))
}

// convertMessageWithTools converts a single Anthropic message to one or more OpenAI messages,
// handling tool_use (-> tool_calls) and tool_result (-> tool role) translations.
func convertMessageWithTools(msg map[string]any, role string) []map[string]any {
	content := msg["content"]
	var results []map[string]any

	switch role {
	case "assistant":
		switch v := content.(type) {
		case string:
			results = append(results, map[string]any{"role": "assistant", "content": v})
		case []any:
			var textParts []string
			var toolCalls []map[string]any
			for _, block := range v {
				cb, ok := block.(map[string]any)
				if !ok {
					continue
				}
				t, _ := cb["type"].(string)
				switch t {
				case "text":
					if text, _ := cb["text"].(string); text != "" {
						textParts = append(textParts, text)
					}
				case "tool_use":
					id, _ := cb["id"].(string)
					name, _ := cb["name"].(string)
					args, _ := json.Marshal(cb["input"])
					toolCalls = append(toolCalls, map[string]any{
						"id":   id,
						"type": "function",
						"function": map[string]any{
							"name":      name,
							"arguments": string(args),
						},
					})
				}
			}
			assistantMsg := map[string]any{"role": "assistant"}
			if len(textParts) > 0 {
				assistantMsg["content"] = strings.Join(textParts, "\n")
			} else if len(toolCalls) > 0 {
				assistantMsg["content"] = nil
			}
			if len(toolCalls) > 0 {
				assistantMsg["tool_calls"] = toolCalls
			}
			if len(textParts) > 0 || len(toolCalls) > 0 {
				results = append(results, assistantMsg)
			}
		default:
			results = append(results, map[string]any{"role": "assistant", "content": content})
		}

	case "user":
		switch v := content.(type) {
		case string:
			results = append(results, map[string]any{"role": "user", "content": v})
		case []any:
			var userParts []map[string]any
			for _, block := range v {
				cb, ok := block.(map[string]any)
				if !ok {
					continue
				}
				t, _ := cb["type"].(string)
				switch t {
				case "text":
					userParts = append(userParts, map[string]any{"type": "text", "text": cb["text"]})
				case "tool_result":
					toolUseID, _ := cb["tool_use_id"].(string)
					toolContent := flattenToolContent(cb["content"])
					results = append(results, map[string]any{
						"role":         "tool",
						"tool_call_id": toolUseID,
						"content":      toolContent,
					})
				}
			}
			if len(userParts) > 0 {
				results = append(results, map[string]any{"role": "user", "content": userParts})
			}
		default:
			results = append(results, map[string]any{"role": "user", "content": content})
		}
	}

	return results
}

// flattenToolContent converts tool_result content (string or content block array) to a plain string.
func flattenToolContent(content any) string {
	switch v := content.(type) {
	case string:
		return v
	case []any:
		var parts []string
		for _, item := range v {
			if m, ok := item.(map[string]any); ok {
				if text, _ := m["text"].(string); text != "" {
					parts = append(parts, text)
				}
			}
		}
		return strings.Join(parts, "\n")
	case nil:
		return ""
	default:
		return fmt.Sprintf("%v", content)
	}
}

// convertToolChoiceToOpenAI converts Anthropic tool_choice to OpenAI format.
func convertToolChoiceToOpenAI(tc any) any {
	switch v := tc.(type) {
	case string:
		return v // "auto", "none"
	case map[string]any:
		tcType, _ := v["type"].(string)
		switch tcType {
		case "tool":
			name, _ := v["name"].(string)
			return map[string]any{
				"type":     "function",
				"function": map[string]any{"name": name},
			}
		case "any":
			return "required"
		default:
			return "auto"
		}
	}
	return "auto"
}

// convertOpenAIResponse reads an OpenAI response and converts back to Anthropic format.
func (p *AnthropicProxy) convertOpenAIResponse(w http.ResponseWriter, resp *http.Response, model string, isStream bool, maskResult *privacy.MaskResult) error {
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		errBody, _ := io.ReadAll(io.LimitReader(resp.Body, maxResponseSize))
		if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
			pipeline := privacy.NewPipeline(&privacy.Config{}, nil)
			errBody = pipeline.UnmaskResponse(errBody, maskResult)
		}
		slog.Warn("vision upstream error", "status", resp.StatusCode, "body", string(errBody))
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(resp.StatusCode)
		w.Write(errBody)
		return nil
	}

	if isStream {
		return p.convertOpenAIStreamResponse(w, resp, model, maskResult)
	}

	body, err := io.ReadAll(io.LimitReader(resp.Body, maxResponseSize))
	if err != nil {
		return fmt.Errorf("read vision response: %w", err)
	}

	var zhipuResp map[string]any
	if err := json.Unmarshal(body, &zhipuResp); err != nil {
		if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
			pipeline := privacy.NewPipeline(&privacy.Config{}, nil)
			body = pipeline.UnmaskResponse(body, maskResult)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(resp.StatusCode)
		w.Write(body)
		return nil
	}

	// Track tokens from Zhipu usage.
	if usage, ok := zhipuResp["usage"].(map[string]any); ok {
		pt, _ := usage["prompt_tokens"].(float64)
		ct, _ := usage["completion_tokens"].(float64)
		p.metrics.RecordTokens(resp.Request.Context(), model, int(pt), int(ct))
		slog.Info("token usage", "model", model, "input", int(pt), "output", int(ct), "format", "zhipu")
	}

	anthropicResp := OpenAIToAnthropic(zhipuResp, model, "")
	respBody, _ := json.Marshal(anthropicResp)

	// Sanitize garbled output BEFORE unmask to avoid stripping restored values.
	respBody = []byte(masking.SanitizeGarbledForModel(model, string(respBody)))

	// Unmask secrets/PII placeholders before sending to client.
	if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
		pipeline := privacy.NewPipeline(&privacy.Config{}, nil)
		respBody = pipeline.UnmaskResponse(respBody, maskResult)
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	w.Write(respBody)
	return nil
}

// ConvertOpenAIStreamResponse converts OpenAI SSE chunks to Anthropic SSE format on-the-fly.
func (p *AnthropicProxy) convertOpenAIStreamResponse(w http.ResponseWriter, resp *http.Response, model string, maskResult *privacy.MaskResult) error {
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	w.WriteHeader(http.StatusOK)
	flusher, _ := w.(http.Flusher)
	if flusher != nil {
		flusher.Flush()
	}

	scanner := bufio.NewScanner(resp.Body)
	scanner.Buffer(make([]byte, 0, 64*1024), maxSSELineSize)

	msgID := fmt.Sprintf("msg_vision_%d", time.Now().UnixNano())
	started := false
	var inputTokens, outputTokens int
	var ttfbRecorded bool
	streamStart := time.Now()

	var unmasker *masking.StreamUnmasker
	if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
		unmasker = masking.NewStreamUnmasker(maskResult.PIICtx, maskResult.SecretsCtx)
		unmasker.SetGLMNoiseMode(strings.HasPrefix(model, "glm-"))
	}

	for scanner.Scan() {
		line := scanner.Text()

		if !strings.HasPrefix(line, "data: ") {
			continue
		}
		data := line[6:]

		if data == "[DONE]" {
			if started {
				// Flush remaining unmasker buffer before closing events.
				if unmasker != nil {
					if remaining := unmasker.Flush(); remaining != "" {
						remaining = masking.SanitizeGarbledForModel(model, remaining)
						if remaining != "" {
							escaped, _ := json.Marshal(remaining)
							fmt.Fprintf(w, "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",\"index\":0,\"delta\":{\"type\":\"text_delta\",\"text\":%s}}\n\n", string(escaped))

						}
					}
				}
				// content_block_stop
				fmt.Fprintf(w, "event: content_block_stop\ndata: {\"type\":\"content_block_stop\",\"index\":0}\n\n")
				// message_delta with stop_reason
				fmt.Fprintf(w, "event: message_delta\ndata: {\"type\":\"message_delta\",\"delta\":{\"stop_reason\":\"end_turn\",\"stop_sequence\":null},\"usage\":{\"output_tokens\":%d}}\n\n", outputTokens)
				// message_stop
				fmt.Fprintf(w, "event: message_stop\ndata: {\"type\":\"message_stop\"}\n\n")
			}
			if flusher != nil {
				flusher.Flush()
			}
			break
		}

		var chunk map[string]any
		if err := json.Unmarshal([]byte(data), &chunk); err != nil {
			continue
		}

		// Extract token usage from chunks.
		if usage, ok := chunk["usage"].(map[string]any); ok {
			if pt, _ := usage["prompt_tokens"].(float64); pt > 0 {
				inputTokens = int(pt)
			}
			if ct, _ := usage["completion_tokens"].(float64); ct > 0 {
				outputTokens = int(ct)
			}
		}

		choices, _ := chunk["choices"].([]any)
		if len(choices) == 0 {
			continue
		}
		choice, _ := choices[0].(map[string]any)
		delta, _ := choice["delta"].(map[string]any)

		// Get text content from delta.
		text, _ := delta["content"].(string)
		// Also check reasoning_content (some Zhipu models use this).
		if text == "" {
			text, _ = delta["reasoning_content"].(string)
		}

		// Flush any partial placeholder buffer before switching to tool_calls
		if unmasker != nil && started {
			if remaining := unmasker.Flush(); remaining != "" {
				remaining = masking.SanitizeGarbledForModel(model, remaining)
				if remaining != "" {
					escaped, _ := json.Marshal(remaining)
					fmt.Fprintf(w, "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",\"index\":0,\"delta\":{\"type\":\"text_delta\",\"text\":%s}}\n\n", string(escaped))

				}
			}
		}
		// Handle tool_calls: forward arguments with unmasking.
		if text == "" {
			if toolCalls, ok := delta["tool_calls"].([]any); ok && len(toolCalls) > 0 {
				for _, tc := range toolCalls {
					tcMap, ok := tc.(map[string]any)
					if !ok {
						continue
					}
					fn, _ := tcMap["function"].(map[string]any)
					args, _ := fn["arguments"].(string)
					if args == "" {
						continue
					}
					if unmasker != nil {
						args = unmasker.ProcessChunkJSON(args)
					}
					if args != "" {
						if !started {
							fmt.Fprintf(w, "event: message_start\ndata: {\"type\":\"message_start\",\"message\":{\"id\":\"%s\",\"type\":\"message\",\"role\":\"assistant\",\"content\":[],\"model\":\"%s\",\"stop_reason\":null,\"stop_sequence\":null,\"usage\":{\"input_tokens\":%d,\"output_tokens\":0}}}\n\n", msgID, model, inputTokens)
							fmt.Fprintf(w, "event: content_block_start\ndata: {\"type\":\"content_block_start\",\"index\":0,\"content_block\":{\"type\":\"text\",\"text\":\"\"}}\n\n")
							started = true
						}
						outputTokens++
						escaped, _ := json.Marshal(args)
						fmt.Fprintf(w, "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",\"index\":0,\"delta\":{\"type\":\"text_delta\",\"text\":%s}}\n\n", string(escaped))
						if flusher != nil {
							flusher.Flush()
						}
					}
				}
			}
			continue
		}

		if !ttfbRecorded {
			p.metrics.RecordTTFB(model, time.Since(streamStart))
			ttfbRecorded = true
		}

		if !started {
			// message_start
			fmt.Fprintf(w, "event: message_start\ndata: {\"type\":\"message_start\",\"message\":{\"id\":\"%s\",\"type\":\"message\",\"role\":\"assistant\",\"content\":[],\"model\":\"%s\",\"stop_reason\":null,\"stop_sequence\":null,\"usage\":{\"input_tokens\":%d,\"output_tokens\":0}}}\n\n", msgID, model, inputTokens)
			// content_block_start
			fmt.Fprintf(w, "event: content_block_start\ndata: {\"type\":\"content_block_start\",\"index\":0,\"content_block\":{\"type\":\"text\",\"text\":\"\"}}\n\n")
			started = true
		}

		outputTokens++

		// Unmask text chunk if privacy masking is active.
		if unmasker != nil {
			text = unmasker.ProcessChunk(text)
			text = masking.SanitizeGarbledForModel(model, text)
		}
		// content_block_delta
		escaped, _ := json.Marshal(text)
		fmt.Fprintf(w, "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",\"index\":0,\"delta\":{\"type\":\"text_delta\",\"text\":%s}}\n\n", string(escaped))
		if flusher != nil {
			flusher.Flush()
		}
	}

	// Emit any remaining unmasker buffer after stream ended without [DONE]
	if unmasker != nil && started {
		if remaining := unmasker.Flush(); remaining != "" {
			remaining = masking.SanitizeGarbledForModel(model, remaining)
			if remaining != "" {
				// Emit closing events for streams that ended without [DONE]
				fmt.Fprintf(w, "event: content_block_stop\ndata: {\"type\":\"content_block_stop\",\"index\":0}\n\n")
				fmt.Fprintf(w, "event: message_delta\ndata: {\"type\":\"message_delta\",\"delta\":{\"stop_reason\":\"end_turn\",\"stop_sequence\":null},\"usage\":{\"output_tokens\":%d}}\n\n", outputTokens)
				fmt.Fprintf(w, "event: message_stop\ndata: {\"type\":\"message_stop\"}\n\n")
				if flusher != nil {
					flusher.Flush()
				}

			}
		}
	}

	if inputTokens > 0 || outputTokens > 0 {
		p.metrics.RecordTokens(resp.Request.Context(), model, inputTokens, outputTokens)
		slog.Info("vision stream token usage", "model", model, "input", inputTokens, "output", outputTokens)
	}

	return nil
}

// OpenAIToAnthropic converts an OpenAI Chat Completions response to Anthropic Messages response format.
func OpenAIToAnthropic(zhipu map[string]any, model string, toolMode ...string) map[string]any {
	content := []any{}
	var stopReason string

	useTools := len(toolMode) > 0 && toolMode[0] == "native"

	if choices, ok := zhipu["choices"].([]any); ok && len(choices) > 0 {
		choice, _ := choices[0].(map[string]any)
		if msg, ok := choice["message"].(map[string]any); ok {
			if text, _ := msg["content"].(string); text != "" {
				content = append(content, map[string]any{"type": "text", "text": text})
			}
			// Convert tool_calls to tool_use content blocks
			if useTools {
				if toolCalls, ok := msg["tool_calls"].([]any); ok {
					for _, tc := range toolCalls {
						tcMap, ok := tc.(map[string]any)
						if !ok {
							continue
						}
						id, _ := tcMap["id"].(string)
						fn, _ := tcMap["function"].(map[string]any)
						name, _ := fn["name"].(string)
						var input any
						if args, _ := fn["arguments"].(string); args != "" {
							json.Unmarshal([]byte(args), &input)
						}
						content = append(content, map[string]any{
							"type":  "tool_use",
							"id":    id,
							"name":  name,
							"input": input,
						})
					}
				}
			}
		}
		if fr, _ := choice["finish_reason"].(string); fr == "stop" {
			stopReason = "end_turn"
		} else if fr == "tool_calls" {
			stopReason = "tool_use"
		} else {
			stopReason = fr
		}
	}

	var inputTokens, outputTokens int
	if usage, ok := zhipu["usage"].(map[string]any); ok {
		if v, ok := usage["prompt_tokens"].(float64); ok {
			inputTokens = int(v)
		}
		if v, ok := usage["completion_tokens"].(float64); ok {
			outputTokens = int(v)
		}
	}

	return map[string]any{
		"id":            zhipu["id"],
		"type":          "message",
		"role":          "assistant",
		"model":         model,
		"content":       content,
		"stop_reason":   stopReason,
		"stop_sequence": nil,
		"usage": map[string]any{
			"input_tokens":  inputTokens,
			"output_tokens": outputTokens,
		},
	}
}

// ProxyOptions configures proxy behavior for non-default upstream/auth scenarios.
type FallbackResult struct {
	APIKey        string
	UpstreamURL   string
	AuthMode      string
	Format        string            // target provider format: "anthropic", "openai", "gemini"
	ModelOverride string            // e.g., "default" for lotuss
	MaxTokens     int               // cap max_tokens in body
	ExtraHeaders  map[string]string // additional headers from provider route
	ToolMode      string            // "native" for OpenAI function calling
}

type ProxyOptions struct {
	AuthMode            string                                       // "api_key" (default) or "bearer"
	UpstreamOverride    string                                       // if non-empty, use this instead of cfg.UpstreamURL
	ExtraHeaders        map[string]string                            // additional headers to set
	Transparent         bool                                         // skip all body/header modifications (claude-oauth passthrough)
	BillingInjected     bool                                         // billing header was injected in Go; return ErrBillingRejected on 400 reserved keyword
	OnAuthError         func(oldKey string) (newKey string, ok bool) // called on 401 to refresh token
	OnRateLimitError    func(oldKey string) (FallbackResult, bool)   // called on 429 to rotate account or fallback provider
	OnForbidden         func(oldKey string) (FallbackResult, bool)   // called on 403 to fallback to another provider
	GetRateLimitBackoff func() time.Duration                         // returns stored rate limit reset duration from Redis on 429
}

var ErrBillingRejected = fmt.Errorf("billing header rejected by upstream (reserved keyword)")

// It tracks token usage via Prometheus and optionally trims verbose responses.
func (p *AnthropicProxy) ProxyTransparent(w http.ResponseWriter, r *http.Request, apiKey string, body []byte, model string, isStream bool, feedback FeedbackFunc, maskResult *privacy.MaskResult, opts *ProxyOptions) error {
	upstreamURL := p.cfg.UpstreamURL + "/v1/messages"
	if opts != nil && opts.UpstreamOverride != "" {
		upstreamURL = opts.UpstreamOverride
	}

	if opts != nil && opts.Transparent {
		upstreamURL = p.cfg.AnthropicDirectURL + "/v1/messages"
		if r.URL.RawQuery != "" {
			upstreamURL += "?" + r.URL.RawQuery
		}
	}

	// Estimate input tokens and log model capabilities.
	estInput := tokenizer.QuickEstimateTokens(string(body))
	modelCap := tokenizer.GetModelCapabilities(model)
	slog.Debug("request token estimate", "model", model, "estimated_input", estInput, "context_limit", modelCap.ContextWindow, "max_output", modelCap.MaxOutputTokens)

	var lastResp *http.Response
	var lastErrBody []byte
	var lastErrStatus int
	currentFormat := "anthropic"
	skipBackoff := false
	streamStarted := false
	var retryAfterOverride time.Duration
	truncationAttempts := 0
	transientAttempts := 0
	maxTransient := p.cfg.TransientRetryMax
	if maxTransient <= 0 {
		maxTransient = 2
	}
	maxAttempts := p.cfg.UpstreamMaxRetries + 1 + maxTransient

	for attempt := 0; attempt < maxAttempts; attempt++ {
		if attempt > 0 && !skipBackoff {
			backoff := p.cfg.UpstreamRetryBaseBackoff * time.Duration(attempt*attempt)
			if retryAfterOverride > 0 {
				backoff = retryAfterOverride
				retryAfterOverride = 0
			}
			// Cap backoff at 5 minutes to prevent excessive waits
			if backoff > 5*time.Minute {
				backoff = 5 * time.Minute
			}
			slog.Warn("upstream retry",
				"attempt", attempt,
				"backoff", backoff,
				"model", model,
				"reason", "429 rate limited",
				"max_attempts", maxAttempts,
			)
			p.metrics.IncRetry()

			if isStream && !streamStarted {
				w.Header().Set("Content-Type", "text/event-stream")
				w.Header().Set("Cache-Control", "no-cache")
				w.Header().Set("Connection", "keep-alive")
				w.WriteHeader(http.StatusOK)
				if f, ok := w.(http.Flusher); ok {
					f.Flush()
				}
				streamStarted = true
			}

			if streamStarted {
				keepAlive := time.NewTicker(2 * time.Second)
				deadline := time.After(backoff)
			waitLoop:
				for {
					select {
					case <-deadline:
						keepAlive.Stop()
						break waitLoop
					case <-keepAlive.C:
						fmt.Fprintf(w, ": retrying attempt %d/%d (%v backoff)\n\n", attempt+1, maxAttempts, backoff)
						if f, ok := w.(http.Flusher); ok {
							f.Flush()
						}
					case <-r.Context().Done():
						keepAlive.Stop()
						return fmt.Errorf("request cancelled during retry backoff: %w", r.Context().Err())
					}
				}
			} else {
				select {
				case <-time.After(backoff):
				case <-r.Context().Done():
					return fmt.Errorf("request cancelled during retry backoff: %w", r.Context().Err())
				}
			}
		} else if attempt > 0 {
			skipBackoff = false
		}

		httpReq, err := http.NewRequestWithContext(r.Context(), http.MethodPost, upstreamURL, bytes.NewReader(body))
		if err != nil {
			return fmt.Errorf("create upstream request: %w", err)
		}
		if opts != nil && opts.Transparent {
			// Transparent passthrough: forward ALL client headers as-is.
			// Preserves exact CLI fingerprint including X-Stainless-*, User-Agent, etc.
			for k, vv := range r.Header {
				httpReq.Header[k] = vv
			}
			// Remove hop-by-hop, host, and proxy-leak headers.
			for _, h := range []string{"Connection", "Keep-Alive", "Proxy-Authenticate", "Proxy-Authorization", "Te", "Trailers", "Transfer-Encoding", "Upgrade", "Host", "Accept-Encoding", "Via", "X-Forwarded-For", "X-Forwarded-Host", "X-Forwarded-Proto"} {
				httpReq.Header.Del(h)
			}
			// Force uncompressed response so SSE/JSON validation works.
			httpReq.Header.Set("Accept-Encoding", "gzip, deflate, zstd")
		} else {
			httpReq.Header.Set("Content-Type", "application/json")
			if opts != nil && opts.AuthMode == "bearer" {
				httpReq.Header.Set("Authorization", "Bearer "+apiKey)
				reqID := r.Header.Get("x-client-request-id")
				if reqID == "" {
					reqID = newRequestID()
				}
				httpReq.Header.Set("x-client-request-id", reqID)
				sessionID := r.Header.Get("X-Claude-Code-Session-Id")
				if sessionID == "" {
					sessionID = newRequestID()
				}
				httpReq.Header.Set("X-Claude-Code-Session-Id", sessionID)
				if bh := r.Header.Get("x-anthropic-billing-header"); bh != "" {
					httpReq.Header.Set("x-anthropic-billing-header", bh)
				}
				if mcpSid := r.Header.Get("x-mcp-client-session-id"); mcpSid != "" {
					httpReq.Header.Set("x-mcp-client-session-id", mcpSid)
				}
			} else {
				httpReq.Header.Set("x-api-key", apiKey)
			}
			httpReq.Header.Set("anthropic-version", p.cfg.AnthropicVersion)
			if opts != nil {
				for k, v := range opts.ExtraHeaders {
					if k == "anthropic-beta" {
						if incoming := r.Header.Get("anthropic-beta"); incoming != "" {
							httpReq.Header.Set(k, mergeBetas(incoming, v))
							continue
						}
					}
					if k == "Accept" && isStream {
						continue
					}
					httpReq.Header.Set(k, v)
				}
			}
			stripUnsupportedBetas(&httpReq.Header, model)
		}
		httpReq.ContentLength = int64(len(body))

		slog.Info("upstream req", "model", model,
			"url", upstreamURL,
			"beta", httpReq.Header.Get("anthropic-beta"),
			"xapp", httpReq.Header.Get("x-app"),
			"ua", httpReq.Header.Get("User-Agent"),
			"session_id", httpReq.Header.Get("x-session-id"),
			"req_id", httpReq.Header.Get("x-client-request-id"),
			"auth", truncate(httpReq.Header.Get("Authorization"), 30),
			"browser_access", httpReq.Header.Get("anthropic-dangerous-direct-browser-access"),
			"apikey", truncate(httpReq.Header.Get("x-api-key"), 30))

		start := time.Now()
		resp, err := p.client.Do(httpReq)
		rtt := time.Since(start)
		if err != nil {
			return fmt.Errorf("upstream call failed: %w", err)
		}

		// Decompress response body for SSE parsing and metrics.
		respEnc := resp.Header.Get("Content-Encoding")
		if respEnc != "" {
			resp.Body = decompressReader(resp.Body, respEnc)
		}

		isLastAttempt := attempt >= maxAttempts-1
		// Report feedback for adaptive limiter only on final attempt
		// to prevent hammering the limit down on retries.
		if feedback != nil && (resp.StatusCode != 429 || isLastAttempt) {
			feedback(resp.StatusCode, rtt, resp.Header)
		}

		if resp.StatusCode == 429 {
			retryAfterSec := resp.Header.Get("Retry-After")
			unifiedReset := resp.Header.Get("Anthropic-Ratelimit-Unified-Reset")
			// Dump ALL response headers for 429 diagnosis.
			allHeaders := make(map[string][]string)
			for k, v := range resp.Header {
				allHeaders[k] = v
			}
			// Read response body for error type diagnosis (max 2KB).
			bodySnippet := ""
			if bodyBytes, err := io.ReadAll(io.LimitReader(resp.Body, 2048)); err == nil {
				bodySnippet = string(bodyBytes)
			}
			slog.Warn("429 rate limit details",
				"attempt", attempt+1,
				"model", model,
				"retry_after", retryAfterSec,
				"unified_reset", unifiedReset,
				"unified_5h_reset", resp.Header.Get("Anthropic-Ratelimit-Unified-5h-Reset"),
				"unified_5h_status", resp.Header.Get("Anthropic-Ratelimit-Unified-5h-Status"),
				"unified_5h_util", resp.Header.Get("Anthropic-Ratelimit-Unified-5h-Utilization"),
				"unified_7d_reset", resp.Header.Get("Anthropic-Ratelimit-Unified-7d-Reset"),
				"all_headers", allHeaders,
				"body", bodySnippet,
			)
			// Parse Retry-After or Unified-Reset Unix timestamp for backoff override.
			if retryAfterSec != "" {
				if secs, err := strconv.Atoi(retryAfterSec); err == nil && secs > 0 {
					retryAfterOverride = time.Duration(secs) * time.Second
					slog.Warn("429 Retry-After override", "wait", retryAfterOverride, "attempt", attempt+1, "model", model)
				}
			} else if unifiedReset != "" {
				if resetTs, err := strconv.ParseInt(unifiedReset, 10, 64); err == nil && resetTs > 0 {
					waitDur := time.Until(time.Unix(resetTs, 0))
					if waitDur > 0 && waitDur < 5*time.Minute {
						retryAfterOverride = waitDur
						slog.Warn("429 Unified-Reset override", "wait", retryAfterOverride, "attempt", attempt+1, "model", model)
					}
				}
			}
			// Fallback: use stored rate limit data from Redis when response has no headers.
			if retryAfterOverride == 0 && opts != nil && opts.GetRateLimitBackoff != nil {
				if backoff := opts.GetRateLimitBackoff(); backoff > 0 {
					retryAfterOverride = backoff
					slog.Warn("429 stored rate limit backoff", "wait", retryAfterOverride, "attempt", attempt+1, "model", model)
				}
			}
			resp.Body.Close()
			p.metrics.Inc429()
			hasFallback := false
			if opts != nil && opts.OnRateLimitError != nil {
				if fb, ok := opts.OnRateLimitError(apiKey); ok {
					hasFallback = true
					apiKey = fb.APIKey
					if strings.HasPrefix(apiKey, "sk-ant-oat01-") {
						r.Header.Set("Authorization", "Bearer "+apiKey)
						r.Header.Del("x-api-key")
					}
					upstreamChanged := fb.UpstreamURL != ""
					if upstreamChanged {
						upstreamURL = fb.UpstreamURL
						opts.Transparent = false
					}
					if fb.AuthMode != "" {
						opts.AuthMode = fb.AuthMode
					}
					if fb.Format != "" && fb.Format != currentFormat {
						body = convertBody(body, model, fb.Format, fb.ToolMode, p.metrics)
						currentFormat = fb.Format
					}
					if fb.ModelOverride != "" {
						body = patchModelInBody(body, fb.ModelOverride)
						model = fb.ModelOverride
					}
					if fb.MaxTokens > 0 {
						body = clampMaxTokensInBody(body, fb.MaxTokens)
					}
					if fb.ExtraHeaders != nil {
						opts.ExtraHeaders = fb.ExtraHeaders
					}
					if upstreamChanged {
						skipBackoff = true
					}
					slog.Info("429 fallback", "attempt", attempt+1, "model", model, "new_upstream", fb.UpstreamURL, "fb_format", fb.Format, "fb_model_override", fb.ModelOverride, "fb_max_tokens", fb.MaxTokens, "current_format", currentFormat, "skip_backoff", upstreamChanged)
				}
			}
			// No fallback: pass 429 to client immediately.
			// Claude CLI has built-in retry (attempt N/10) and handles backoff itself.
			// Server-side retry causes 502 when client cancels during backoff sleep.
			if !hasFallback {
				if retryAfterOverride > 0 {
					slog.Info("429 passthrough to client", "model", model, "retry_after", retryAfterOverride)
				} else {
					slog.Info("429 passthrough to client", "model", model, "retry_after", "none")
				}
				w.Header().Set("Content-Type", "application/json")
				w.Header().Set("X-Should-Retry", "true")
				retrySeconds := int(retryAfterOverride.Seconds())
				if retrySeconds <= 0 {
					retrySeconds = 15
				}
				w.Header().Set("Retry-After", strconv.Itoa(retrySeconds))
				w.WriteHeader(429)
				w.Write([]byte(bodySnippet))
				return nil
			}
			continue
		}

		// On 403, try fallback to another provider in the profile.
		if resp.StatusCode == 403 && opts != nil && opts.OnForbidden != nil {
			resp.Body.Close()
			if fb, ok := opts.OnForbidden(apiKey); ok {
				slog.Warn("403 forbidden, falling back to alternate provider", "model", model, "new_upstream", fb.UpstreamURL)
				apiKey = fb.APIKey
				if fb.UpstreamURL != "" {
					upstreamURL = fb.UpstreamURL
					opts.Transparent = false
				}
				if fb.AuthMode != "" {
					opts.AuthMode = fb.AuthMode
				}
				skipBackoff = true
				continue
			}
		}

		// On 401 with OAuth bearer, try refreshing the token once.
		if resp.StatusCode == 401 && opts != nil && opts.AuthMode == "bearer" && opts.OnAuthError != nil && !opts.Transparent {
			resp.Body.Close()
			if newKey, ok := opts.OnAuthError(apiKey); ok {
				slog.Warn("upstream retry with refreshed token", "model", model, "status", resp.StatusCode)
				apiKey = newKey
				httpReq, err := http.NewRequestWithContext(r.Context(), http.MethodPost, upstreamURL, bytes.NewReader(body))
				if err != nil {
					return fmt.Errorf("create retry request: %w", err)
				}
				httpReq.Header.Set("Content-Type", "application/json")
				httpReq.Header.Set("Authorization", "Bearer "+apiKey)
				reqID := r.Header.Get("x-client-request-id")
				if reqID == "" {
					reqID = newRequestID()
				}
				httpReq.Header.Set("x-client-request-id", reqID)
				sessionID := r.Header.Get("X-Claude-Code-Session-Id")
				if sessionID == "" {
					sessionID = newRequestID()
				}
				httpReq.Header.Set("X-Claude-Code-Session-Id", sessionID)
				httpReq.Header.Set("anthropic-version", p.cfg.AnthropicVersion)
				for k, v := range opts.ExtraHeaders {
					httpReq.Header.Set(k, v)
				}
				httpReq.ContentLength = int64(len(body))

				start2 := time.Now()
				resp2, err2 := p.client.Do(httpReq)
				rtt2 := time.Since(start2)
				if err2 != nil {
					return fmt.Errorf("retry after refresh failed: %w", err2)
				}
				if enc := resp2.Header.Get("Content-Encoding"); enc != "" {
					resp2.Body = decompressReader(resp2.Body, enc)
				}

				if feedback != nil {
					feedback(resp2.StatusCode, rtt2, resp2.Header)
				}
				lastResp = resp2
				break
			}
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(401)
			json.NewEncoder(w).Encode(ErrorResponse{
				Type: "error",
				Error: ErrorDetail{
					Type:    "authentication_error",
					Message: "OAuth token expired and refresh failed. Please re-authenticate.",
				},
			})
			return fmt.Errorf("upstream 401: token refresh failed")
		}

		// On 401 in transparent mode with OAuth token, attempt refresh.
		// Transparent mode normally forwards client headers as-is, but if
		// the upstream rejects with 401, we can refresh the OAuth token.
		if resp.StatusCode == 401 && opts != nil && opts.Transparent && opts.OnAuthError != nil {
			resp.Body.Close()
			if newKey, ok := opts.OnAuthError(apiKey); ok {
				slog.Warn("upstream retry with refreshed transparent token", "model", model, "status", resp.StatusCode)
				apiKey = newKey
				httpReq, err := http.NewRequestWithContext(r.Context(), http.MethodPost, upstreamURL, bytes.NewReader(body))
				if err != nil {
					return fmt.Errorf("create retry request: %w", err)
				}
				// Forward all client headers (transparent mode) with refreshed token.
				for k, vv := range r.Header {
					httpReq.Header[k] = vv
				}
				httpReq.Header.Set("Authorization", "Bearer "+apiKey)
				httpReq.Header.Del("x-api-key")
				for _, h := range []string{"Connection", "Keep-Alive", "Proxy-Authenticate", "Proxy-Authorization", "Te", "Trailers", "Transfer-Encoding", "Upgrade", "Host", "Accept-Encoding", "Via", "X-Forwarded-For", "X-Forwarded-Host", "X-Forwarded-Proto"} {
					httpReq.Header.Del(h)
				}
				httpReq.Header.Set("Accept-Encoding", "gzip, deflate, zstd")
				httpReq.ContentLength = int64(len(body))
				start2 := time.Now()
				resp2, err2 := p.client.Do(httpReq)
				rtt2 := time.Since(start2)
				if err2 != nil {
					return fmt.Errorf("retry after refresh failed: %w", err2)
				}
				if enc := resp2.Header.Get("Content-Encoding"); enc != "" {
					resp2.Body = decompressReader(resp2.Body, enc)
				}

				if feedback != nil {
					feedback(resp2.StatusCode, rtt2, resp2.Header)
				}
				lastResp = resp2
				break
			}
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(401)
			json.NewEncoder(w).Encode(ErrorResponse{
				Type: "error",
				Error: ErrorDetail{
					Type:    "authentication_error",
					Message: "OAuth token expired and refresh failed. Please re-authenticate.",
				},
			})
			return fmt.Errorf("upstream 401: transparent token refresh failed")
		}

		if resp.StatusCode == http.StatusOK {
			// Validate response is not empty/malformed before treating as success
			if !isStream {
				// For non-streaming, peek at the body to verify it's valid JSON
				peekBuf := make([]byte, 1024)
				n, _ := io.ReadFull(resp.Body, peekBuf)
				if n == 0 {
					// Empty response - treat as transient error
					resp.Body.Close()
					p.metrics.IncTransientRetry(200, model)
					slog.Warn("upstream returned empty response (HTTP 200), retrying",
						"model", model,
						"attempt", attempt,
						"max_attempts", maxAttempts,
					)
					if transientAttempts >= maxTransient {
						lastErrBody = []byte("empty response body")
						lastErrStatus = 200
						break
					}
					transientAttempts++
					lastErrBody = []byte("empty response body")
					lastErrStatus = 200
					continue
				}
				// Check if the peeked data looks like valid JSON start
				peeked := strings.TrimSpace(string(peekBuf[:n]))
				if len(peeked) == 0 || (peeked[0] != '{' && peeked[0] != '[') {
					// Not valid JSON start - treat as transient error
					resp.Body.Close()
					p.metrics.IncTransientRetry(200, model)
					slog.Warn("upstream returned malformed response (HTTP 200), retrying",
						"model", model,
						"attempt", attempt,
						"peek_preview", peeked[:min(200, len(peeked))],
						"max_attempts", maxAttempts,
					)
					if transientAttempts >= maxTransient {
						lastErrBody = peekBuf[:n]
						lastErrStatus = 200
						break
					}
					transientAttempts++
					lastErrBody = peekBuf[:n]
					lastErrStatus = 200
					continue
				}
				// Valid response - recreate body reader with full content
				lastResp = resp
				lastResp.Body = struct {
					io.Reader
					io.Closer
				}{
					Reader: io.MultiReader(bytes.NewReader(peekBuf[:n]), resp.Body),
					Closer: resp.Body,
				}
				lastErrBody = nil
				break
			} else {
				// For streaming, peek at first SSE chunk to verify stream is alive.
				// Use single Read() instead of io.ReadFull to avoid blocking until
				// 1024 bytes arrive - SSE events are typically 200-400 bytes each.
				peekBuf := make([]byte, 1024)
				n, _ := resp.Body.Read(peekBuf)
				if n == 0 {
					resp.Body.Close()
					p.metrics.IncTransientRetry(200, model)
					slog.Warn("upstream returned empty stream (HTTP 200), retrying",
						"model", model,
						"attempt", attempt,
						"max_attempts", maxAttempts,
					)
					if transientAttempts >= maxTransient {
						lastErrBody = []byte("empty stream")
						lastErrStatus = 200
						break
					}
					transientAttempts++
					lastErrBody = []byte("empty stream")
					lastErrStatus = 200
					continue
				}
				// Check if we got at least one valid SSE line
				peeked := string(peekBuf[:n])
				hasValidSSE := false
				for _, line := range strings.Split(peeked, "\n") {
					trimmed := strings.TrimSpace(line)
					if strings.HasPrefix(trimmed, "data:") || strings.HasPrefix(trimmed, "event:") {
						hasValidSSE = true
						break
					}
				}
				if !hasValidSSE {
					resp.Body.Close()
					p.metrics.IncTransientRetry(200, model)
					slog.Warn("upstream returned malformed stream (HTTP 200), retrying",
						"model", model,
						"attempt", attempt,
						"peek_preview", peeked[:min(200, len(peeked))],
						"max_attempts", maxAttempts,
					)
					if transientAttempts >= maxTransient {
						lastErrBody = peekBuf[:n]
						lastErrStatus = 200
						break
					}
					transientAttempts++
					lastErrBody = peekBuf[:n]
					lastErrStatus = 200
					continue
				}
				// Valid stream - recreate body reader with peeked data
				lastResp = resp
				lastResp.Body = struct {
					io.Reader
					io.Closer
				}{
					Reader: io.MultiReader(bytes.NewReader(peekBuf[:n]), resp.Body),
					Closer: resp.Body,
				}
				lastErrBody = nil
				break
			}
		}

		errBody, readErr := io.ReadAll(io.LimitReader(resp.Body, maxResponseSize))
		resp.Body.Close()
		if readErr != nil {
			lastErrBody = []byte(readErr.Error())
			lastErrStatus = resp.StatusCode
			break
		}
		lastErrBody = errBody
		lastErrStatus = resp.StatusCode
		if resp.StatusCode >= 400 {
			slog.Warn("upstream error response", "status", resp.StatusCode, "model", model,
				"body", string(errBody[:min(500, len(errBody))]))
		}

		// If billing was injected and upstream rejected with reserved keyword,
		// return early so handler can fall back to sidecar.
		if opts != nil && opts.BillingInjected && resp.StatusCode == 400 && strings.Contains(string(errBody), "reserved keyword") {
			if streamStarted {
				slog.Error("billing rejected after SSE stream committed, cannot fall back to sidecar", "model", model)
				w.Write([]byte("event: error\ndata: {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":\"billing rejected\"}}\n\n"))
				if f, ok := w.(http.Flusher); ok {
					f.Flush()
				}
				return nil
			}
			slog.Warn("Go billing injection rejected by upstream, returning ErrBillingRejected", "model", model)
			return ErrBillingRejected
		}

		action := ClassifyError(resp.StatusCode, errBody)
		switch action {
		case ActionTruncateAndRetry:
			if truncationAttempts >= 1 || !p.cfg.EnableAutoTruncate {
				break
			}
			result := TruncateMessages(body, model)
			if result == nil {
				break
			}
			truncationAttempts++
			body = result.Body
			p.metrics.IncContextTruncation(model)
			slog.Info("auto-truncated conversation", "model", model,
				"dropped_messages", result.DroppedMsgs, "orig_tokens", result.OrigTokens,
				"new_tokens", result.NewTokens)
			lastErrBody = nil
			continue
		case ActionRetryTransient:
			if transientAttempts >= maxTransient {
				break
			}
			transientAttempts++
			p.metrics.IncTransientRetry(resp.StatusCode, model)
			slog.Warn("upstream retry transient error",
				"status", resp.StatusCode,
				"model", model,
				"retry", transientAttempts,
				"max_transient", maxTransient,
				"response", string(errBody[:min(200, len(errBody))]),
			)
			lastErrBody = nil
			continue
		}
		break
	}

	if lastResp == nil {
		if streamStarted {
			// SSE stream already committed - send error event through the stream.
			errMsg := "upstream error after retries"
			if len(lastErrBody) > 0 {
				errMsg = string(lastErrBody[:min(500, len(lastErrBody))])
			}
			slog.Error("upstream failed after SSE stream started, sending error event",
				"model", model, "last_status", lastErrStatus, "error", errMsg)
			errJSON, _ := json.Marshal(ErrorResponse{
				Type: "error",
				Error: ErrorDetail{
					Type:    "api_error",
					Message: "rate limited: " + errMsg,
				},
			})
			fmt.Fprintf(w, "event: error\ndata: %s\n\n", errJSON)
			if f, ok := w.(http.Flusher); ok {
				f.Flush()
			}
			return nil
		}
		if len(lastErrBody) > 0 {
			if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
				pipeline := privacy.NewPipeline(&privacy.Config{}, nil)
				lastErrBody = pipeline.UnmaskResponse(lastErrBody, maskResult)
			}
			// Validate JSON before writing. If upstream sent truncated JSON,
			// wrap in a proper error response so client doesn't get "Unexpected EOF".
			if !json.Valid(lastErrBody) {
				slog.Warn("upstream error body is not valid JSON, wrapping",
					"status", lastErrStatus,
					"body_preview", string(lastErrBody[:min(200, len(lastErrBody))]),
				)
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusBadGateway)
				json.NewEncoder(w).Encode(ErrorResponse{
					Type: "error",
					Error: ErrorDetail{
						Type:    "api_error",
						Message: "upstream returned malformed error response",
					},
				})
				return nil
			}
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(lastErrStatus)
			w.Write(lastErrBody)
			return nil
		}
		slog.Error("upstream all retries exhausted",
			"model", model,
			"max_attempts", maxAttempts,
			"last_status", lastErrStatus,
			"last_error", string(lastErrBody[:min(200, len(lastErrBody))]),
		)
		return fmt.Errorf("upstream returned no response after %d retries", maxAttempts)
	}
	defer lastResp.Body.Close()

	if isStream {
		// Stream: write headers only if not already sent during retry keep-alive.
		if !streamStarted {
			copyResponseHeaders(w, lastResp)
			w.WriteHeader(lastResp.StatusCode)
			// Flush headers immediately so client sees HTTP 200 without waiting
			// for the first SSE data line from upstream.
			if f, ok := w.(http.Flusher); ok {
				f.Flush()
			}
		}

		var unmasker *masking.StreamUnmasker
		if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
			unmasker = masking.NewStreamUnmasker(maskResult.PIICtx, maskResult.SecretsCtx)
			// Enable "undefined" fallback for:
			// 1. OAuth passthrough (opts.Transparent) - Claude OAuth converts placeholders to "undefined"
			// 2. GLM models - same issue
			// Standard Anthropic API (with API keys) preserves placeholders correctly.
			enableFallback := (opts != nil && opts.Transparent) || strings.HasPrefix(model, "glm-")
			unmasker.SetGLMNoiseMode(enableFallback)
		}
		return p.relayStreamWithTracking(w, lastResp, model, unmasker, estInput, maskResult)
	}

	// Non-stream: buffer full response before writing headers so errors
	// can still return a proper JSON error instead of empty body -> "Unexpected EOF".
	return p.handleNonStreamResponse(w, lastResp, model, maskResult)
}

const (
	billingSalt     = "59cf53e54c78"
	billingVersion  = "2.1.123"
	billingPrefix   = "x-anthropic-billing-header: "
	billingIdentity = "You are Claude Code, Anthropic's official CLI for Claude."
)

// injectBillingHeader modifies the request body to inject the Claude Code billing
// header as system[0] and identity string as system[1], matching the CLI's algorithm.
func InjectBillingHeader(body []byte) []byte {
	var req map[string]any
	if json.Unmarshal(body, &req) != nil {
		return body
	}

	firstText := extractFirstUserText(req)
	buildHash := computeBuildHash(firstText)
	headerStr := fmt.Sprintf("cc_version=%s.%s; cc_entrypoint=cli; cch=00000;", billingVersion, buildHash)
	billingEntry := map[string]string{"type": "text", "text": billingPrefix + headerStr}
	identityEntry := map[string]string{"type": "text", "text": billingIdentity}

	system, _ := req["system"]
	switch s := system.(type) {
	case nil:
		req["system"] = []any{billingEntry, identityEntry}
	case string:
		req["system"] = []any{billingEntry, identityEntry, map[string]string{"type": "text", "text": s}}
	case []any:
		for _, item := range s {
			if m, ok := item.(map[string]any); ok {
				if t, _ := m["text"].(string); strings.HasPrefix(t, billingPrefix) {
					return body // already has billing header
				}
			}
		}
		hasIdentity := false
		for _, item := range s {
			if m, ok := item.(map[string]any); ok {
				if t, _ := m["text"].(string); t == billingIdentity {
					hasIdentity = true
					break
				}
			}
		}
		entries := []any{billingEntry}
		if !hasIdentity {
			entries = append(entries, identityEntry)
		}
		req["system"] = append(entries, s...)
	}

	newBody, err := json.Marshal(req)
	if err != nil {
		return body
	}
	return newBody
}

func extractFirstUserText(req map[string]any) string {
	msgs, ok := req["messages"].([]any)
	if !ok {
		return ""
	}
	for _, m := range msgs {
		msg, ok := m.(map[string]any)
		if !ok {
			continue
		}
		if role, _ := msg["role"].(string); role != "user" {
			continue
		}
		if _, isMeta := msg["isMeta"]; isMeta {
			continue
		}
		c := msg["content"]
		switch content := c.(type) {
		case string:
			return content
		case []any:
			for _, b := range content {
				block, ok := b.(map[string]any)
				if !ok {
					continue
				}
				if t, _ := block["type"].(string); t == "text" {
					if text, _ := block["text"].(string); text != "" {
						return text
					}
				}
			}
		}
	}
	return ""
}

func computeBuildHash(text string) string {
	chars := []byte{'0', '0', '0'}
	for i, idx := range []int{4, 7, 20} {
		if idx < len(text) {
			chars[i] = text[idx]
		}
	}
	h := sha256.Sum256([]byte(billingSalt + string(chars) + billingVersion))
	return fmt.Sprintf("%x", h)[:3]
}

// ProxySidecar forwards the request to a local Node.js sidecar that injects
// the Claude Code billing header into the system prompt before proxying to
// api.anthropic.com. This routes requests to the Claude Code rate limit bucket
// instead of the generic OAuth bucket.
func (p *AnthropicProxy) ProxySidecar(w http.ResponseWriter, r *http.Request, sidecarURL string, body []byte, model string, isStream bool, feedback FeedbackFunc, maskResult *privacy.MaskResult, opts *ProxyOptions) error {
	httpReq, err := http.NewRequestWithContext(r.Context(), http.MethodPost, sidecarURL+r.URL.Path+"?beta=true", bytes.NewReader(body))
	if err != nil {
		return fmt.Errorf("create sidecar request: %w", err)
	}
	// Forward ALL client headers (same as transparent mode).
	for k, vv := range r.Header {
		httpReq.Header[k] = vv
	}
	for _, h := range []string{"Connection", "Keep-Alive", "Proxy-Authenticate", "Proxy-Authorization", "Te", "Trailers", "Transfer-Encoding", "Upgrade", "Host", "Via", "X-Forwarded-For", "X-Forwarded-Host", "X-Forwarded-Proto"} {
		httpReq.Header.Del(h)
	}
	httpReq.ContentLength = int64(len(body))

	slog.Info("sidecar proxy req", "model", model, "url", sidecarURL+r.URL.Path, "transparent", true)

	start := time.Now()
	resp, err := p.client.Do(httpReq)
	rtt := time.Since(start)
	if err != nil {
		return fmt.Errorf("sidecar call failed: %w", err)
	}
	defer resp.Body.Close()

	if feedback != nil {
		feedback(resp.StatusCode, rtt, resp.Header)
	}

	if resp.StatusCode == 400 {
		errBody, _ := io.ReadAll(io.LimitReader(resp.Body, 4096))
		if strings.Contains(string(errBody), "reserved keyword") {
			slog.Warn("sidecar billing header rejected (reserved keyword)", "model", model, "status", 400)
			return fmt.Errorf("sidecar: billing header rejected by upstream (reserved keyword)")
		}
		// Relay non-reserved-keyword 400s as-is.
	}

	// Copy response headers.
	for k, vs := range resp.Header {
		if _, ok := allowedResponseHeaders[k]; !ok {
			continue
		}
		for _, v := range vs {
			w.Header().Add(k, v)
		}
	}
	w.WriteHeader(resp.StatusCode)
	if f, ok := w.(http.Flusher); ok {
		f.Flush()
	}

	if isStream {
		var unmasker *masking.StreamUnmasker
		if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
			unmasker = masking.NewStreamUnmasker(maskResult.PIICtx, maskResult.SecretsCtx)
			// Enable "undefined" fallback for:
			// 1. OAuth passthrough - Claude OAuth converts placeholders to "undefined"
			// 2. GLM models - same issue
			// Sidecar is always transparent (OAuth mode).
			enableFallback := true || strings.HasPrefix(model, "glm-")
			unmasker.SetGLMNoiseMode(enableFallback)
		}

		flusher, _ := w.(http.Flusher)
		scanner := bufio.NewScanner(resp.Body)
		scanner.Buffer(make([]byte, 0, 64*1024), maxSSELineSize)

		var sidecarInputTokens, sidecarOutputTokens int
		var lastUnmaskBlockIdx int = -1
		sidecarBlockTypes := map[int]string{}

		for scanner.Scan() {
			line := scanner.Text()

			if unmasker != nil {
				if strings.HasPrefix(line, "data: ") {
					data := line[6:]
					// Track token usage from SSE events.
					if strings.Contains(data, "message_start") {
						var msg struct {
							Message struct {
								Usage struct {
									InputTokens              int `json:"input_tokens"`
									CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
									CacheReadInputTokens     int `json:"cache_read_input_tokens"`
								} `json:"usage"`
							} `json:"message"`
						}
						if json.Unmarshal([]byte(data), &msg) == nil {
							sidecarInputTokens = msg.Message.Usage.InputTokens + msg.Message.Usage.CacheCreationInputTokens + msg.Message.Usage.CacheReadInputTokens
							p.metrics.RecordCacheUsage(model, msg.Message.Usage.CacheCreationInputTokens, msg.Message.Usage.CacheReadInputTokens)
						}
					} else if strings.Contains(data, "message_delta") {
						var msg struct {
							Usage struct {
								OutputTokens int `json:"output_tokens"`
							} `json:"usage"`
						}
						if json.Unmarshal([]byte(data), &msg) == nil && msg.Usage.OutputTokens > 0 {
							sidecarOutputTokens = msg.Usage.OutputTokens
						}
					}

					if strings.Contains(data, `"content_block_start"`) {
						var bs struct {
							Index        int `json:"index"`
							ContentBlock struct {
								Type string `json:"type"`
							} `json:"content_block"`
						}
						if json.Unmarshal([]byte(data), &bs) == nil && bs.ContentBlock.Type != "" {
							sidecarBlockTypes[bs.Index] = bs.ContentBlock.Type
						}
					}

					if strings.Contains(data, `"content_block_delta"`) {
						var evt struct {
							Type  string `json:"type"`
							Index int    `json:"index"`
							Delta struct {
								Type           string          `json:"type"`
								Text           string          `json:"text,omitempty"`
								Thinking       string          `json:"thinking,omitempty"`
								PartialJSON    string          `json:"partial_json,omitempty"`
								InputJSONDelta string          `json:"input_json_delta,omitempty"`
								Signature      string          `json:"signature,omitempty"`
								Citations      json.RawMessage `json:"citations,omitempty"`
							} `json:"delta"`
						}
						if json.Unmarshal([]byte(data), &evt) == nil {
							// Flush on block index change to prevent cross-block buffer contamination
							if evt.Index != lastUnmaskBlockIdx && lastUnmaskBlockIdx >= 0 {
								if remaining := unmasker.Flush(); remaining != "" {
									emitUnmaskerFlush(w, masking.SanitizeGarbledForModel(model, remaining), lastUnmaskBlockIdx, sidecarBlockTypes[lastUnmaskBlockIdx])
								}
							}
							lastUnmaskBlockIdx = evt.Index

							var changed bool
							if evt.Delta.Text != "" {
								before := evt.Delta.Text
								evt.Delta.Text = unmasker.ProcessChunk(evt.Delta.Text)
								evt.Delta.Text = masking.SanitizeGarbledForModel(model, evt.Delta.Text)
								changed = evt.Delta.Text != before
							} else if evt.Delta.Thinking != "" {
								before := evt.Delta.Thinking
								evt.Delta.Thinking = unmasker.ProcessChunk(evt.Delta.Thinking)
								evt.Delta.Thinking = masking.SanitizeGarbledForModel(model, evt.Delta.Thinking)
								changed = evt.Delta.Thinking != before
							} else if evt.Delta.PartialJSON != "" {
								before := evt.Delta.PartialJSON
								evt.Delta.PartialJSON = unmasker.ProcessChunkJSON(evt.Delta.PartialJSON)
								evt.Delta.PartialJSON = masking.SanitizeGarbledForModel(model, evt.Delta.PartialJSON)
								changed = evt.Delta.PartialJSON != before
							} else if evt.Delta.InputJSONDelta != "" {
								before := evt.Delta.InputJSONDelta
								evt.Delta.InputJSONDelta = unmasker.ProcessChunkJSON(evt.Delta.InputJSONDelta)
								evt.Delta.InputJSONDelta = masking.SanitizeGarbledForModel(model, evt.Delta.InputJSONDelta)
								changed = evt.Delta.InputJSONDelta != before
							}
							if changed {
								if newData, err := json.Marshal(evt); err == nil {
									line = "data: " + string(newData)
								}
							}
						}
					} else if strings.Contains(data, `"content_block_stop"`) {
						if sidecarInputTokens > 0 || sidecarOutputTokens > 0 {
							p.metrics.RecordTokens(r.Context(), model, sidecarInputTokens, sidecarOutputTokens)
							slog.Debug("sidecar stream token usage",
								"model", model,
								"input", sidecarInputTokens,
								"output", sidecarOutputTokens,
							)
						}

						if remaining := unmasker.Flush(); remaining != "" {
							emitUnmaskerFlush(w, masking.SanitizeGarbledForModel(model, remaining), lastUnmaskBlockIdx, sidecarBlockTypes[lastUnmaskBlockIdx])
						}
					} else if strings.Contains(data, "[[") {
						unmasked := unmasker.ReplaceDirectJSON(data)
						if unmasked != data {
							line = "data: " + unmasked
						}
					}
				}
			}

			// Sanitize garbled "undefined" in content_block_delta when unmasker is inactive.
			if unmasker == nil && strings.HasPrefix(line, "data: ") {
				data := line[6:]
				if strings.Contains(data, `"content_block_delta"`) {
					var evt struct {
						Type  string `json:"type"`
						Index int    `json:"index"`
						Delta struct {
							Type     string `json:"type"`
							Text     string `json:"text,omitempty"`
							Thinking string `json:"thinking,omitempty"`
						} `json:"delta"`
					}
					if json.Unmarshal([]byte(data), &evt) == nil {
						var sanitized bool
						if evt.Delta.Text != "" {
							clean := masking.SanitizeGarbledForModel(model, evt.Delta.Text)
							if clean != evt.Delta.Text {
								evt.Delta.Text = clean
								sanitized = true
							}
						}
						if evt.Delta.Thinking != "" {
							clean := masking.SanitizeGarbledForModel(model, evt.Delta.Thinking)
							if clean != evt.Delta.Thinking {
								evt.Delta.Thinking = clean
								sanitized = true
							}
						}
						if sanitized {
							if newData, err := json.Marshal(evt); err == nil {
								line = "data: " + string(newData)
							}
						}
					}
				}
			}

			fmt.Fprintln(w, line)

			if flusher != nil {
				flusher.Flush()
			}
		}

		if unmasker != nil {
			if remaining := unmasker.Flush(); remaining != "" {
				emitUnmaskerFlush(w, masking.SanitizeGarbledForModel(model, remaining), lastUnmaskBlockIdx, sidecarBlockTypes[lastUnmaskBlockIdx])
			}
		}
		return nil
	}

	respBody, err := io.ReadAll(io.LimitReader(resp.Body, maxResponseSize))
	if err != nil {
		return fmt.Errorf("read sidecar response: %w", err)
	}

	// Sanitize garbled output BEFORE unmask to avoid stripping restored values.
	respBody = []byte(masking.SanitizeGarbledForModel(model, string(respBody)))

	if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
		pipeline := privacy.NewPipeline(&privacy.Config{}, nil)
		respBody = pipeline.UnmaskResponse(respBody, maskResult)
	}

	// Track token usage for non-stream sidecar responses.
	var nsUsage struct {
		Usage struct {
			InputTokens              int `json:"input_tokens"`
			OutputTokens             int `json:"output_tokens"`
			CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
			CacheReadInputTokens     int `json:"cache_read_input_tokens"`
		} `json:"usage"`
	}
	if json.Unmarshal(respBody, &nsUsage) == nil {
		totalInput := nsUsage.Usage.InputTokens + nsUsage.Usage.CacheCreationInputTokens + nsUsage.Usage.CacheReadInputTokens
		p.metrics.RecordCacheUsage(model, nsUsage.Usage.CacheCreationInputTokens, nsUsage.Usage.CacheReadInputTokens)
		if totalInput > 0 || nsUsage.Usage.OutputTokens > 0 {
			p.metrics.RecordTokens(r.Context(), model, totalInput, nsUsage.Usage.OutputTokens)
		}
	}

	// Convert GLM <details><summary> HTML to markdown.
	if strings.HasPrefix(model, "glm-") {
		respBody = convertHTMLDetails(respBody)
	}
	w.Write(respBody)
	return nil
}

// copyResponseHeaders copies allowed upstream response headers to the client writer.
func copyResponseHeaders(w http.ResponseWriter, resp *http.Response) {
	for k, vs := range resp.Header {
		if _, ok := allowedResponseHeaders[k]; !ok {
			continue
		}
		for _, v := range vs {
			w.Header().Add(k, v)
		}
	}
}

// handleNonStreamResponse buffers the full response, tracks tokens, optionally trims, and sends.
const maxResponseSize = 100 * 1024 * 1024 // 100MB limit

func (p *AnthropicProxy) handleNonStreamResponse(w http.ResponseWriter, resp *http.Response, model string, maskResult *privacy.MaskResult) error {
	// Limit response size to prevent OOM
	limitedReader := io.LimitReader(resp.Body, maxResponseSize+1)
	body, err := io.ReadAll(limitedReader)
	if err != nil {
		return fmt.Errorf("read response: %w", err)
	}
	if len(body) > maxResponseSize {
		return fmt.Errorf("response exceeds maximum size of %d bytes", maxResponseSize)
	}

	// Track token usage.
	tokenTracked := false
	var usage struct {
		Usage struct {
			InputTokens              int `json:"input_tokens"`
			OutputTokens             int `json:"output_tokens"`
			CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
			CacheReadInputTokens     int `json:"cache_read_input_tokens"`
		} `json:"usage"`
	}
	if json.Unmarshal(body, &usage) == nil {
		totalInput := usage.Usage.InputTokens + usage.Usage.CacheCreationInputTokens + usage.Usage.CacheReadInputTokens
		p.metrics.RecordCacheUsage(model, usage.Usage.CacheCreationInputTokens, usage.Usage.CacheReadInputTokens)
		if totalInput > 0 || usage.Usage.OutputTokens > 0 {
			p.metrics.RecordTokens(resp.Request.Context(), model, totalInput, usage.Usage.OutputTokens)
			slog.Info("token usage",
				"model", model,
				"input", totalInput,
				"output", usage.Usage.OutputTokens,
				"cache_creation", usage.Usage.CacheCreationInputTokens,
				"cache_read", usage.Usage.CacheReadInputTokens,
				"format", "anthropic",
			)
			tokenTracked = true
		}
	}

	if !tokenTracked {
		// Log raw response for debugging when token tracking fails.
		preview := string(body)
		if len(preview) > 500 {
			preview = preview[:500]
		}
		slog.Warn("token tracking failed for non-stream response",
			"model", model,
			"status", resp.StatusCode,
			"body_preview", preview,
		)
		// Fallback: try parsing without nested "usage" wrapper (OpenAI-style)
		var altUsage struct {
			InputTokens      int `json:"input_tokens"`
			OutputTokens     int `json:"output_tokens"`
			PromptTokens     int `json:"prompt_tokens"`
			CompletionTokens int `json:"completion_tokens"`
		}
		if json.Unmarshal(body, &altUsage) == nil {
			in := altUsage.InputTokens
			out := altUsage.OutputTokens
			if in == 0 && altUsage.PromptTokens > 0 {
				in = altUsage.PromptTokens
			}
			if out == 0 && altUsage.CompletionTokens > 0 {
				out = altUsage.CompletionTokens
			}
			if in > 0 || out > 0 {
				p.metrics.RecordTokens(resp.Request.Context(), model, in, out)
				slog.Info("token usage (fallback format)",
					"model", model,
					"input", in,
					"output", out,
				)
			}
		}
		slog.Debug("token usage not found in response",
			"model", model,
			"response_preview", string(body[:min(500, len(body))]),
		)
	}

	// Sanitize garbled output BEFORE unmask to avoid stripping restored values.
	body = []byte(masking.SanitizeGarbledForModel(model, string(body)))

	// Unmask secrets/PII placeholders before trimming so placeholders stay intact.
	if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
		slog.Info("unmask debug",
			"has_secrets", maskResult.HasSecrets,
			"has_pii", maskResult.HasPII,
			"secrets_mapping_count", len(maskResult.SecretsCtx.Mapping),
			"pii_mapping_count", len(maskResult.PIICtx.Mapping),
			"body_preview", string(body[:min(300, len(body))]),
		)
		pipeline := privacy.NewPipeline(&privacy.Config{}, nil)
		body = pipeline.UnmaskResponse(body, maskResult)
		slog.Info("unmask result", "body_preview", string(body[:min(300, len(body))]))
	} else {
		slog.Info("unmask skipped", "maskResult_nil", maskResult == nil)
	}

	// Trim verbose patterns after unmasking.
	if p.cfg.EnableResponseTrim {
		if trimmed, charsSaved := trimResponse(body); trimmed != nil {
			body = trimmed
			if charsSaved > 0 {
				p.metrics.RecordOptimization("response_trim", charsSaved, "output")
				tokensSaved := int(float64(charsSaved) / 4.0)
				p.metrics.RecordTokensSaved(tokensSaved, "output")
				p.metrics.RecordCostSavings(model, float64(tokensSaved)*p.metrics.GetInputPrice(model)/1_000_000)
			}
		}
	}
	// Convert GLM <details><summary> HTML to markdown.
	if strings.HasPrefix(model, "glm-") {
		body = convertHTMLDetails(body)
	}
	// Validate JSON before writing to client. If upstream sent truncated JSON
	// (e.g. connection reset mid-body), wrap it in a valid error response so
	// the client gets parseable JSON instead of "Unexpected EOF".
	if !json.Valid(body) {
		slog.Warn("upstream returned invalid JSON, wrapping as error",
			"model", model,
			"status", resp.StatusCode,
			"body_len", len(body),
			"body_preview", string(body[:min(200, len(body))]),
		)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(ErrorResponse{
			Type: "error",
			Error: ErrorDetail{
				Type:    "api_error",
				Message: "upstream returned malformed response",
			},
		})
		return nil
	}

	// Write headers only after body is fully buffered so errors above can still
	// return a proper JSON error to the caller without "headers already sent".
	copyResponseHeaders(w, resp)
	w.WriteHeader(resp.StatusCode)
	_, err = w.Write(body)
	return err
}

const streamTimeout = 10 * time.Minute

// emitUnmaskerFlush writes the unmasker's buffered remainder as a content_block_delta
// whose delta type matches the open block's type. Emitting a text_delta into a
// thinking or tool_use block makes the Anthropic SDK / Claude Code crash with
// "Content block is not a text block", so the delta type must match blockType.
func emitUnmaskerFlush(w io.Writer, remaining string, idx int, blockType string) {
	if remaining == "" || idx < 0 {
		return
	}
	escaped, _ := json.Marshal(remaining)
	deltaType, field := "text_delta", "text"
	switch blockType {
	case "thinking":
		deltaType, field = "thinking_delta", "thinking"
	case "tool_use":
		deltaType, field = "input_json_delta", "partial_json"
	case "redacted_thinking":
		return // cannot append deltas to a redacted_thinking block
	}
	fmt.Fprintf(w, "event: content_block_delta\ndata: {\"type\":\"content_block_delta\",\"index\":%d,\"delta\":{\"type\":%q,%q:%s}}\n\n", idx, deltaType, field, string(escaped))
}

func (p *AnthropicProxy) relayStreamWithTracking(w http.ResponseWriter, resp *http.Response, model string, unmasker *masking.StreamUnmasker, fallbackInputTokens int, maskResult *privacy.MaskResult) error {
	// Add timeout to prevent hanging streams
	ctx, cancel := context.WithTimeout(resp.Request.Context(), streamTimeout)
	defer cancel()

	// Wrap body with context-aware reader
	body := &readCloser{Reader: io.NopCloser(resp.Body), ctx: ctx}

	scanner := bufio.NewScanner(body)
	scanner.Buffer(make([]byte, 0, 64*1024), maxSSELineSize)

	// GLM models emit <details><summary> and XML tool blocks in streaming text.
	var stripper *toolUseStripper
	if strings.HasPrefix(model, "glm-") {
		stripper = &toolUseStripper{}
	}

	if maskResult != nil && (maskResult.HasSecrets || maskResult.HasPII) {
		slog.Info("stream unmasker active", "has_secrets", maskResult.HasSecrets, "has_pii", maskResult.HasPII,
			"secrets_map", len(maskResult.SecretsCtx.Mapping), "pii_map", len(maskResult.PIICtx.Mapping),
			"unmasker_has_ctx", unmasker != nil && unmasker.HasContexts())
	}
	// Count how many chunks get unmasked for debugging.
	var unmaskHits int
	defer func() {
		if unmaskHits > 0 {
			slog.Info("stream unmask hits", "count", unmaskHits)
		}
	}()

	var ttfbRecorded bool
	var inputTokens, outputTokens int
	var lastRelayBlockIdx = -1
	blockTypes := map[int]string{}
	var streamStart = time.Now()
	for scanner.Scan() {
		if !ttfbRecorded {
			p.metrics.RecordTTFB(model, time.Since(streamStart))
			ttfbRecorded = true
		}
		line := scanner.Text()

		// Parse SSE data lines for unmasking and token tracking.
		if !strings.HasPrefix(line, "data: ") {
			fmt.Fprintln(w, line)
			if f, ok := w.(http.Flusher); ok {
				f.Flush()
			}
			continue
		}
		data := line[6:]

		// Unmask placeholders and sanitize garbled output in SSE data lines.
		// SanitizeGarbledOutput runs even without unmasker to catch repeated
		// "undefined" from GLM models regardless of masking state.
		if strings.Contains(data, `"content_block_delta"`) {
			var evt struct {
				Type  string `json:"type"`
				Index int    `json:"index"`
				Delta struct {
					Type           string          `json:"type"`
					Text           string          `json:"text,omitempty"`
					Thinking       string          `json:"thinking,omitempty"`
					PartialJSON    string          `json:"partial_json,omitempty"`
					InputJSONDelta string          `json:"input_json_delta,omitempty"`
					Signature      string          `json:"signature,omitempty"`
					Citations      json.RawMessage `json:"citations,omitempty"`
				} `json:"delta"`
			}
			if json.Unmarshal([]byte(data), &evt) == nil {
				// Flush on block index change to prevent cross-block buffer contamination
				if unmasker != nil && evt.Index != lastRelayBlockIdx && lastRelayBlockIdx >= 0 {
					if remaining := unmasker.Flush(); remaining != "" {
						emitUnmaskerFlush(w, masking.SanitizeGarbledForModel(model, remaining), lastRelayBlockIdx, blockTypes[lastRelayBlockIdx])
					}
				}
				if unmasker != nil {
					lastRelayBlockIdx = evt.Index
				}

				var changed bool
				if evt.Delta.Text != "" {
					before := evt.Delta.Text
					if stripper != nil {
						evt.Delta.Text = stripper.Feed(evt.Delta.Text)
					}
					if unmasker != nil {
						evt.Delta.Text = unmasker.ProcessChunk(evt.Delta.Text)
					}
					if stripper != nil {
						evt.Delta.Text = masking.SanitizeGarbledForModel(model, evt.Delta.Text)
					}
					changed = evt.Delta.Text != before
				} else if evt.Delta.Thinking != "" {
					before := evt.Delta.Thinking
					if unmasker != nil {
						evt.Delta.Thinking = unmasker.ProcessChunk(evt.Delta.Thinking)
					}
					if stripper != nil {
						evt.Delta.Thinking = masking.SanitizeGarbledForModel(model, evt.Delta.Thinking)
					}
					changed = evt.Delta.Thinking != before
				} else if evt.Delta.PartialJSON != "" && unmasker != nil {
					before := evt.Delta.PartialJSON
					evt.Delta.PartialJSON = unmasker.ProcessChunkJSON(evt.Delta.PartialJSON)
					if stripper != nil {
						evt.Delta.PartialJSON = masking.SanitizeGarbledForModel(model, evt.Delta.PartialJSON)
					}
					changed = evt.Delta.PartialJSON != before
				} else if evt.Delta.InputJSONDelta != "" && unmasker != nil {
					before := evt.Delta.InputJSONDelta
					evt.Delta.InputJSONDelta = unmasker.ProcessChunkJSON(evt.Delta.InputJSONDelta)
					if stripper != nil {
						evt.Delta.InputJSONDelta = masking.SanitizeGarbledForModel(model, evt.Delta.InputJSONDelta)
					}
					changed = evt.Delta.InputJSONDelta != before
				}
				if changed {
					unmaskHits++
					if newData, err := json.Marshal(evt); err == nil {
						line = "data: " + string(newData)
					}
				}
				// Fallback: structured handler didn't match, but data contains [[ placeholders.
				if !changed && unmasker != nil && strings.Contains(data, "[[") {
					unmasked := unmasker.ReplaceDirectJSON(data)
					if unmasked != data {
						unmaskHits++
						line = "data: " + unmasked
					}
				}
			}
		} else if unmasker != nil && strings.Contains(data, "[[") {
			unmasked := unmasker.ReplaceDirectJSON(data)
			if unmasked != data {
				unmaskHits++
				line = "data: " + unmasked
			}
		}

		// Flush unmasker buffer at content block boundaries to prevent
		// cross-block contamination (e.g. text buffer leaking into thinking).
		if unmasker != nil && strings.Contains(data, `"content_block_stop"`) {
			if remaining := unmasker.Flush(); remaining != "" {
				emitUnmaskerFlush(w, masking.SanitizeGarbledForModel(model, remaining), lastRelayBlockIdx, blockTypes[lastRelayBlockIdx])
			}
		}

		// Relay to client.
		fmt.Fprintln(w, line)
		if f, ok := w.(http.Flusher); ok {
			f.Flush()
		}

		if strings.Contains(data, `"content_block_start"`) {
			var bs struct {
				Index        int `json:"index"`
				ContentBlock struct {
					Type string `json:"type"`
				} `json:"content_block"`
			}
			if json.Unmarshal([]byte(data), &bs) == nil && bs.ContentBlock.Type != "" {
				blockTypes[bs.Index] = bs.ContentBlock.Type
			}
		}

		if strings.Contains(data, `"message_start"`) {
			var msg struct {
				Message struct {
					Usage struct {
						InputTokens              int `json:"input_tokens"`
						CacheCreationInputTokens int `json:"cache_creation_input_tokens"`
						CacheReadInputTokens     int `json:"cache_read_input_tokens"`
					} `json:"usage"`
				} `json:"message"`
			}
			if json.Unmarshal([]byte(data), &msg) == nil {
				total := msg.Message.Usage.InputTokens + msg.Message.Usage.CacheCreationInputTokens + msg.Message.Usage.CacheReadInputTokens
				p.metrics.RecordCacheUsage(model, msg.Message.Usage.CacheCreationInputTokens, msg.Message.Usage.CacheReadInputTokens)
				if total > 0 {
					inputTokens = total
				}
			}
		} else if strings.Contains(data, `"message_delta"`) {
			var msg struct {
				Delta struct {
					StopReason string `json:"stop_reason"`
				} `json:"delta"`
				Usage struct {
					OutputTokens int `json:"output_tokens"`
				} `json:"usage"`
			}
			if json.Unmarshal([]byte(data), &msg) == nil {
				if msg.Usage.OutputTokens > 0 {
					outputTokens = msg.Usage.OutputTokens
				}
				if msg.Delta.StopReason != "" {
					slog.Info("glm stop_reason", "stop_reason", msg.Delta.StopReason, "model", model)
				}
			}
		}
	}

	if err := scanner.Err(); err != nil {
		isClientGone := ctx.Err() != nil
		slog.Warn("anthropic stream scanner error", "error", err, "client_gone", isClientGone, "output_tokens", outputTokens, "elapsed", time.Since(streamStart).Round(time.Millisecond))
		if isClientGone {
			// Flush unmasker buffer before emitting closing events to prevent placeholder leaks
			if unmasker != nil {
				if remaining := unmasker.Flush(); remaining != "" {
					emitUnmaskerFlush(w, masking.SanitizeGarbledForModel(model, remaining), lastRelayBlockIdx, blockTypes[lastRelayBlockIdx])
				}
			}
			return nil
		}
		if f, ok := w.(http.Flusher); ok {
			f.Flush()
		}
		errMsg, _ := json.Marshal(err.Error())
		fmt.Fprintf(w, "event: error\ndata: {\"type\":\"error\",\"error\":{\"type\":\"api_error\",\"message\":%s}}\n\n", string(errMsg))
		fmt.Fprintf(w, "event: message_delta\ndata: {\"type\":\"message_delta\",\"delta\":{\"stop_reason\":\"end_turn\",\"stop_sequence\":null},\"usage\":{\"output_tokens\":%d}}\n\n", outputTokens)
		fmt.Fprintf(w, "event: message_stop\ndata: {\"type\":\"message_stop\"}\n\n")
		if f, ok := w.(http.Flusher); ok {
			f.Flush()
		}
		return fmt.Errorf("stream scanner error: %w", err)
	}

	// Flush GLM HTML/XML stripper before unmasker.
	if stripper != nil {
		if remaining := stripper.Flush(); remaining != "" {
			remaining = masking.SanitizeGarbledForModel(model, remaining)
			if remaining != "" {
				slog.Info("stripper flushed remaining", "len", len(remaining))

			}
		}
	}

	// Emit any remaining unmasker buffer as a final content_block_delta.
	if unmasker != nil {
		if remaining := unmasker.Flush(); remaining != "" {
			remaining = masking.SanitizeGarbledForModel(model, remaining)
			if remaining != "" {
				emitUnmaskerFlush(w, remaining, lastRelayBlockIdx, blockTypes[lastRelayBlockIdx])
				slog.Warn("unmask buffer not empty at stream end, emitted as delta", "remaining_len", len(remaining))
			}
		}
	}

	// Fallback: use estimated input tokens if upstream didn't report them.
	if inputTokens == 0 && fallbackInputTokens > 0 {
		inputTokens = fallbackInputTokens
	}

	if inputTokens > 0 || outputTokens > 0 {
		p.metrics.RecordTokens(ctx, model, inputTokens, outputTokens)
		slog.Debug("stream token usage",
			"model", model,
			"input", inputTokens,
			"output", outputTokens,
		)
	}

	return nil
}

// convertHTMLDetails converts <details><summary> HTML in text content blocks to markdown.
// Only applied for GLM models that emit these tags as formatting noise.

func convertHTMLDetails(body []byte) []byte {
	var resp map[string]any
	if json.Unmarshal(body, &resp) != nil {
		return body
	}
	content, ok := resp["content"].([]any)
	if !ok {
		return body
	}
	modified := false
	for i, block := range content {
		cb, ok := block.(map[string]any)
		if !ok || cb["type"] != "text" {
			continue
		}
		text, ok := cb["text"].(string)
		if !ok {
			continue
		}
		if !strings.Contains(text, "<details") && !strings.Contains(text, "<summary") {
			continue
		}
		text = htmlDetailTagRe.ReplaceAllString(text, "")
		text = htmlSummaryTagRe.ReplaceAllString(text, "**$1**\n")
		cb["text"] = text
		content[i] = cb
		modified = true
	}
	if !modified {
		return body
	}
	resp["content"] = content
	result, err := json.Marshal(resp)
	if err != nil {
		return body
	}
	return result
}

// trimResponse strips verbose patterns from text content blocks in a non-stream response.
// Returns nil if trimming was skipped (invalid JSON or no changes).
// Returns the trimmed bytes and number of chars saved if trimming occurred.
func trimResponse(body []byte) ([]byte, int) {
	var resp map[string]any
	if json.Unmarshal(body, &resp) != nil {
		return nil, 0
	}

	content, ok := resp["content"].([]any)
	if !ok {
		return nil, 0
	}

	modified := false
	totalCharsSaved := 0
	for i, block := range content {
		cb, ok := block.(map[string]any)
		if !ok || cb["type"] != "text" {
			continue
		}
		text, ok := cb["text"].(string)
		if !ok {
			continue
		}
		trimmed := trimVerbose(text)
		if trimmed != text {
			if !isValidUTF8String(trimmed) {
				slog.Warn("trimmed text contains invalid UTF-8, skipping trim")
				continue
			}
			totalCharsSaved += len(text) - len(trimmed)
			cb["text"] = trimmed
			content[i] = cb
			modified = true
		}
	}

	if !modified {
		return nil, 0
	}

	resp["content"] = content
	result, err := json.Marshal(resp)
	if err != nil {
		return nil, 0
	}
	return result, totalCharsSaved
}

// trimVerbose removes common verbose prefixes and suffixes from AI response text.
func trimVerbose(text string) string {
	for _, re := range verbosePatterns {
		text = re.ReplaceAllString(text, "")
	}
	return strings.TrimSpace(text)
}

var verbosePatterns = []*regexp.Regexp{
	regexp.MustCompile(`(?i)^here's (the |a )?`),
	regexp.MustCompile(`(?i)^here is (the |a )?`),
	regexp.MustCompile(`(?i)^let me (explain|help|show|walk you through|break down|tell you about)[^\n]*\n`),
	regexp.MustCompile(`(?i)^i'll (help you|explain|show|walk you through)[^\n]*\n`),
	regexp.MustCompile(`(?i)^sure!?\s*\n`),
	regexp.MustCompile(`(?i)^certainly!?\s*\n`),
	regexp.MustCompile(`(?i)^of course!?\s*\n`),
	regexp.MustCompile(`(?i)^great question!?\s*\n`),
	regexp.MustCompile(`(?i)^i'd be happy to (help|explain|show|assist)[^\n]*\n`),
	regexp.MustCompile(`(?i)\n\nhope (this|that) (helps|is helpful)!?\.?\s*$`),
	regexp.MustCompile(`(?i)\n\nlet me know if you need (anything else|more help|further assistance)\.?\s*$`),
}

// readCloser wraps an io.Reader with context cancellation support.
type readCloser struct {
	io.Reader
	ctx context.Context
}

func (rc *readCloser) Read(p []byte) (n int, err error) {
	if err := rc.ctx.Err(); err != nil {
		return 0, err
	}
	return rc.Reader.Read(p)
}

// isValidUTF8String checks if a string contains only valid printable UTF-8.
func isValidUTF8String(s string) bool {
	if !utf8.ValidString(s) {
		return false
	}
	for _, r := range s {
		if r < 0x20 && r != '\t' && r != '\n' && r != '\r' {
			return false
		}
	}
	return true
}

// newRequestID generates a random UUID-like request ID for x-client-request-id.
func newRequestID() string {
	b := make([]byte, 16)
	rand.Read(b)
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:])
}

// mergeBets combines two comma-separated beta header strings, deduplicating entries.
func mergeBetas(incoming, extra string) string {
	seen := make(map[string]bool)
	var result []string
	for _, s := range strings.Split(incoming+","+extra, ",") {
		s = strings.TrimSpace(s)
		if s != "" && !seen[s] {
			seen[s] = true
			result = append(result, s)
		}
	}
	return strings.Join(result, ",")
}

// RateLimitError returns an Anthropic-format rate limit error.
func RateLimitError(retryAfterSec int) ErrorResponse {
	return ErrorResponse{
		Type: "error",
		Error: ErrorDetail{
			Type:    "rate_limit_error",
			Message: fmt.Sprintf("Rate limit exceeded. Please retry after %d seconds.", retryAfterSec),
		},
	}
}

// OverloadedError returns an Anthropic-format overloaded error.
func OverloadedError(msg string) ErrorResponse {
	return ErrorResponse{
		Type: "error",
		Error: ErrorDetail{
			Type:    "overloaded_error",
			Message: msg,
		},
	}
}
func patchModelInBody(body []byte, newModel string) []byte {
	var m map[string]any
	if err := json.Unmarshal(body, &m); err != nil {
		return body
	}
	m["model"] = newModel
	out, err := json.Marshal(m)
	if err != nil {
		return body
	}
	return out
}

func clampMaxTokensInBody(body []byte, max int) []byte {
	var m map[string]any
	if err := json.Unmarshal(body, &m); err != nil {
		return body
	}
	if v, ok := m["max_tokens"]; ok {
		switch val := v.(type) {
		case float64:
			if int(val) > max {
				m["max_tokens"] = max
			}
		case int:
			if val > max {
				m["max_tokens"] = max
			}
		}
	}
	out, err := json.Marshal(m)
	if err != nil {
		return body
	}
	return out
}

func convertBody(body []byte, model, targetFormat, toolMode string, m *metrics.Metrics) []byte {
	if targetFormat == "openai" {
		converted, err := AnthropicToOpenAI(body, model, m, toolMode)
		if err != nil {
			slog.Warn("body format conversion failed", "target", targetFormat, "error", err)
			return body
		}
		out, err := json.Marshal(converted)
		if err != nil {
			return body
		}
		return out
	}
	return body
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
