{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "ai-gateway.component" (dict "Release" .Release "Chart" .Chart "component" "proxy") }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ai-gateway.labels" (dict "Chart" .Chart "Release" .Release "component" "proxy") | nindent 4 }}
spec:
  gateways:
    - {{ .Values.istio.gateway }}
  hosts:
    {{- toYaml .Values.istio.hosts | nindent 4 }}
  http:
    - route:
        - destination:
            host: {{ include "ai-gateway.component" (dict "Release" .Release "Chart" .Chart "component" "proxy") }}
            port:
              number: {{ .Values.proxy.service.port }}
      timeout: 300s
{{- end }}
