package metrics

import (
	"io"
	"log"
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const namespace = "api_gateway"

// Metrics holds all Prometheus instruments for the API gateway.
type Metrics struct {
	RequestLatency    *prometheus.HistogramVec
	QueueDepth        prometheus.GaugeFunc
	ErrorRate         *prometheus.CounterVec
	RateLimitHits     *prometheus.CounterVec
	ActiveConnections prometheus.Gauge
	TokenInput        *prometheus.CounterVec
	TokenOutput       *prometheus.CounterVec
	UpstreamRetries   prometheus.Counter
	Upstream429       prometheus.Counter
	registry          *prometheus.Registry
	queueDepthFn      func() float64
}

// New creates and registers all Prometheus metrics. The queueDepthFn callback
// is invoked on every scrape to report the current queue length.
func New(queueDepthFn func() float64) *Metrics {
	registry := prometheus.NewRegistry()

	m := &Metrics{
		registry:     registry,
		queueDepthFn: queueDepthFn,

		RequestLatency: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "request_latency_seconds",
			Help:      "Latency of HTTP requests in seconds.",
			Buckets:   []float64{0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60},
		}, []string{"method", "path", "status"}),

		ErrorRate: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "error_total",
			Help:      "Total number of errors by type.",
		}, []string{"type"}),

		RateLimitHits: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "rate_limit_hits_total",
			Help:      "Total number of rate-limited requests.",
		}, []string{"key"}),

		ActiveConnections: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "active_connections",
			Help:      "Current number of active connections.",
		}),

		TokenInput: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "token_input_total",
			Help:      "Total input tokens consumed by model.",
		}, []string{"model"}),

		TokenOutput: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "token_output_total",
			Help:      "Total output tokens generated by model.",
		}, []string{"model"}),

		UpstreamRetries: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "upstream_retries_total",
			Help:      "Total number of upstream retries on 429.",
		}),

		Upstream429: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "upstream_429_total",
			Help:      "Total number of 429 responses received from upstream.",
		}),
	}

	m.QueueDepth = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Name:      "queue_depth",
		Help:      "Current depth of the AI job queue.",
	}, queueDepthFn)

	registry.MustRegister(
		m.RequestLatency,
		m.QueueDepth,
		m.ErrorRate,
		m.RateLimitHits,
		m.ActiveConnections,
		m.TokenInput,
		m.TokenOutput,
		m.UpstreamRetries,
		m.Upstream429,
	)

	return m
}

// Handler returns an HTTP handler that serves Prometheus metrics.
func (m *Metrics) Handler() http.Handler {
	return promhttp.HandlerFor(m.registry, promhttp.HandlerOpts{
		ErrorLog: log.New(io.Discard, "", 0),
	})
}

// statusWriter wraps http.ResponseWriter to capture the actual status code.
type statusWriter struct {
	http.ResponseWriter
	status int
}

func newStatusWriter(w http.ResponseWriter) *statusWriter {
	return &statusWriter{ResponseWriter: w, status: http.StatusOK}
}

func (sw *statusWriter) WriteHeader(code int) {
	sw.status = code
	sw.ResponseWriter.WriteHeader(code)
}

// Middleware instruments every request with latency and active-connection tracking.
func (m *Metrics) Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		m.ActiveConnections.Inc()
		defer m.ActiveConnections.Dec()

		sw := newStatusWriter(w)
		start := time.Now()

		next.ServeHTTP(sw, r)

		routePattern := chi.RouteContext(r.Context()).RoutePattern()
		if routePattern == "" {
			routePattern = r.URL.Path
		}

		status := strconv.Itoa(sw.status)
		duration := time.Since(start).Seconds()
		m.RequestLatency.WithLabelValues(r.Method, routePattern, status).Observe(duration)
	})
}

// IncError increments the error counter for the given error type.
func (m *Metrics) IncError(errType string) {
	m.ErrorRate.WithLabelValues(errType).Inc()
}

// IncRateLimit increments the rate-limit counter for the given key.
func (m *Metrics) IncRateLimit(key string) {
	m.RateLimitHits.WithLabelValues(key).Inc()
}

// RecordTokens records input and output token usage for a model.
func (m *Metrics) RecordTokens(model string, input, output int) {
	if input > 0 {
		m.TokenInput.WithLabelValues(model).Add(float64(input))
	}
	if output > 0 {
		m.TokenOutput.WithLabelValues(model).Add(float64(output))
	}
}

// IncRetry increments the upstream retry counter.
func (m *Metrics) IncRetry() {
	m.UpstreamRetries.Inc()
}

// Inc429 increments the upstream 429 counter.
func (m *Metrics) Inc429() {
	m.Upstream429.Inc()
}
