package metrics

import (
	"bufio"
	"context"
	"crypto/sha1"
	"encoding/hex"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
)

const namespace = "api_gateway"

// Metrics holds all Prometheus instruments for the API gateway.
type Metrics struct {
	RequestLatency        *prometheus.HistogramVec
	QueueDepth            prometheus.GaugeFunc
	ErrorRate             *prometheus.CounterVec
	RateLimitHits         *prometheus.CounterVec
	ActiveConnections     prometheus.Gauge
	TokenInput            *prometheus.CounterVec
	TokenOutput           *prometheus.CounterVec
	UpstreamRetries       prometheus.Counter
	Upstream429           prometheus.Counter
	AdaptiveLimit         *prometheus.GaugeVec
	AdaptiveInFlight      *prometheus.GaugeVec
	CostTotal             *prometheus.CounterVec
	ModelFallback         *prometheus.CounterVec
	TTFB                  *prometheus.HistogramVec
	ProfileRequests       *prometheus.CounterVec
	ProfileTokenIn        *prometheus.CounterVec
	ProfileTokenOut       *prometheus.CounterVec
	ProfileCost           *prometheus.CounterVec
	AccountTokenIn        *prometheus.CounterVec
	AccountTokenOut       *prometheus.CounterVec
	OptimizerCharsSaved   *prometheus.CounterVec
	OptimizerRuns         *prometheus.CounterVec
	OptimizerDuration     *prometheus.HistogramVec
	OptimizerTokensSaved  *prometheus.CounterVec
	ProfileOptimizerSaved *prometheus.CounterVec
	BudgetLevel           *prometheus.GaugeVec
	CostSavings           *prometheus.CounterVec
	ContextTruncations    *prometheus.CounterVec
	TransientRetries      *prometheus.CounterVec
	BillingPathRequests   *prometheus.CounterVec
	BillingPathLatency    *prometheus.HistogramVec
	WasteFindings         *prometheus.CounterVec
	WasteTokensWasted     *prometheus.CounterVec
	MCPCallsTotal         *prometheus.CounterVec
	MCPCallDuration       *prometheus.HistogramVec
	MCPCacheHits          *prometheus.CounterVec
	MCPCacheMisses        *prometheus.CounterVec
	MCPQuotaUsage         *prometheus.GaugeVec
	ImageCompressions     *prometheus.CounterVec
	ImageBytesSaved       *prometheus.CounterVec
	ImageBytesOriginal    *prometheus.CounterVec
	VisionPreAnalysis     *prometheus.CounterVec
	VisionPreAnalysisDur  *prometheus.HistogramVec
	CacheCreationTokens   *prometheus.CounterVec
	CacheReadTokens       *prometheus.CounterVec
	CacheSavingsTotal     *prometheus.CounterVec
	ClaudeProfileFetches  *prometheus.CounterVec
	ClaudeProfileErrors   *prometheus.CounterVec
	ClaudeOrgTier         *prometheus.GaugeVec
	ClaudeSubStatus       *prometheus.GaugeVec
	ClaudeRoleCount       *prometheus.GaugeVec
	registry              *prometheus.Registry
	queueDepthFn          func() float64
	pricing               map[string]modelPrice
	usageRecorder         func(ctx context.Context, model string, input, output int, cost float64)
}

type modelPrice struct {
	inputPerMillion  float64
	outputPerMillion float64
}

// New creates and registers all Prometheus metrics. The queueDepthFn callback
// is invoked on every scrape to report the current queue length.
func New(queueDepthFn func() float64, pricing map[string][2]float64) *Metrics {
	registry := prometheus.NewRegistry()

	// Convert pricing map.
	pm := make(map[string]modelPrice, len(pricing))
	for model, prices := range pricing {
		pm[model] = modelPrice{inputPerMillion: prices[0], outputPerMillion: prices[1]}
	}

	m := &Metrics{
		registry:     registry,
		queueDepthFn: queueDepthFn,
		pricing:      pm,

		RequestLatency: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "request_latency_seconds",
			Help:      "Latency of HTTP requests in seconds.",
			Buckets:   []float64{0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60},
		}, []string{"method", "path", "status"}),

		ErrorRate: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "error_total",
			Help:      "Total number of errors by type.",
		}, []string{"type"}),

		RateLimitHits: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "rate_limit_hits_total",
			Help:      "Total number of rate-limited requests.",
		}, []string{"key"}),

		ActiveConnections: prometheus.NewGauge(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "active_connections",
			Help:      "Current number of active connections.",
		}),

		TokenInput: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "token_input_total",
			Help:      "Total input tokens consumed by model.",
		}, []string{"model"}),

		TokenOutput: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "token_output_total",
			Help:      "Total output tokens generated by model.",
		}, []string{"model"}),

		UpstreamRetries: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "upstream_retries_total",
			Help:      "Total number of upstream retries on 429.",
		}),

		Upstream429: prometheus.NewCounter(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "upstream_429_total",
			Help:      "Total number of 429 responses received from upstream.",
		}),

		AdaptiveLimit: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "adaptive_limit",
			Help:      "Current adaptive concurrency limit per model.",
		}, []string{"model"}),

		AdaptiveInFlight: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "adaptive_in_flight",
			Help:      "Current in-flight requests per model.",
		}, []string{"model"}),

		CostTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "cost_total",
			Help:      "Estimated cost in USD by model, calculated from token usage * configured pricing.",
		}, []string{"model", "type"}),

		ModelFallback: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "model_fallback_total",
			Help:      "Number of times a request was routed to a different model.",
		}, []string{"requested", "selected"}),

		TTFB: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "ttfb_seconds",
			Help:      "Time to first byte for streaming responses.",
			Buckets:   []float64{0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5},
		}, []string{"model"}),

		ProfileRequests: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "profile_requests_total",
			Help:      "Total requests per profile per model.",
		}, []string{"profile", "model"}),

		ProfileTokenIn: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "profile_token_input_total",
			Help:      "Total input tokens consumed per profile per model.",
		}, []string{"profile", "model"}),

		ProfileTokenOut: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "profile_token_output_total",
			Help:      "Total output tokens generated per profile per model.",
		}, []string{"profile", "model"}),

		ProfileCost: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "profile_cost_total",
			Help:      "Estimated cost in USD per profile per model.",
		}, []string{"profile", "model", "type"}),

		AccountTokenIn: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "account_token_input_total",
			Help:      "Total input tokens consumed per account per model.",
		}, []string{"account_id", "model"}),

		AccountTokenOut: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "account_token_output_total",
			Help:      "Total output tokens generated per account per model.",
		}, []string{"account_id", "model"}),

		OptimizerCharsSaved: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "optimizer_chars_saved_total",
			Help:      "Total characters saved by token optimization techniques.",
		}, []string{"technique", "direction"}),

		OptimizerRuns: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "optimizer_runs_total",
			Help:      "Total number of optimization runs by technique.",
		}, []string{"technique"}),

		ContextTruncations: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "context_truncation_total",
			Help:      "Total number of auto-truncation recovery attempts by model.",
		}, []string{"model"}),

		TransientRetries: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "transient_retry_total",
			Help:      "Total number of transient error retries by status code and model.",
		}, []string{"status", "model"}),

		BillingPathRequests: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "billing_path_requests_total",
			Help:      "Total Claude OAuth billing path requests by path (go_direct, sidecar, direct, billing_rejected).",
		}, []string{"path", "model", "profile"}),

		BillingPathLatency: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "billing_path_latency_seconds",
			Help:      "Latency of billing header injection and upstream call by path.",
			Buckets:   []float64{0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10, 30, 60},
		}, []string{"path", "model"}),

		OptimizerDuration: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "optimizer_duration_seconds",
			Help:      "Duration of optimization technique execution.",
			Buckets:   []float64{0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1},
		}, []string{"technique"}),

		OptimizerTokensSaved: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "optimizer_tokens_saved_total",
			Help:      "Total estimated tokens saved by optimization.",
		}, []string{"direction"}),

		ProfileOptimizerSaved: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "profile_optimizer_chars_saved_total",
			Help:      "Total characters saved by optimization per profile.",
		}, []string{"profile", "technique"}),

		BudgetLevel: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "budget_level",
			Help:      "Current budget utilization level per model (0=green, 1=yellow, 2=red).",
		}, []string{"model"}),

		CostSavings: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "cost_savings_total",
			Help:      "Total estimated cost savings from optimization in USD by model.",
		}, []string{"model"}),
		WasteFindings: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "waste_findings_total",
			Help:      "Total waste findings detected by detector and severity.",
		}, []string{"detector", "severity"}),

		WasteTokensWasted: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "waste_tokens_wasted_total",
			Help:      "Total tokens identified as wasted by detector.",
		}, []string{"detector"}),

		MCPCallsTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "mcp_calls_total",
			Help:      "Total MCP proxy calls by server, tool, and status.",
		}, []string{"server", "tool", "status"}),
		MCPCallDuration: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "mcp_call_duration_seconds",
			Help:      "Duration of MCP proxy calls by server and tool.",
			Buckets:   []float64{0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10},
		}, []string{"server", "tool"}),
		MCPCacheHits: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "mcp_cache_hits_total",
			Help:      "Total MCP cache hits by server and tool.",
		}, []string{"server", "tool"}),
		MCPCacheMisses: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "mcp_cache_misses_total",
			Help:      "Total MCP cache misses by server and tool.",
		}, []string{"server", "tool"}),
		MCPQuotaUsage: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "mcp_quota_usage",
			Help:      "Current MCP call count in the rate-limit window by account.",
		}, []string{"account_id"}),

		ImageCompressions: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "image_compressions_total",
			Help:      "Number of images compressed via bimg/libvips.",
		}, []string{"model"}),

		ImageBytesSaved: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "image_bytes_saved_total",
			Help:      "Bytes saved by image compression.",
		}, []string{"model"}),

		ImageBytesOriginal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "image_bytes_original_total",
			Help:      "Original bytes of images before compression.",
		}, []string{"model"}),

		VisionPreAnalysis: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "vision_preanalysis_total",
			Help:      "Vision pre-analysis calls (status: success or fallback).",
		}, []string{"status"}),

		VisionPreAnalysisDur: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: namespace,
			Name:      "vision_preanalysis_duration_seconds",
			Help:      "Duration of vision pre-analysis API call.",
			Buckets:   []float64{1, 3, 5, 10, 20, 30, 60, 120},
		}, []string{}),

		CacheCreationTokens: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "cache_creation_tokens_total",
			Help:      "Total tokens written to prompt cache by model.",
		}, []string{"model"}),

		CacheReadTokens: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "cache_read_tokens_total",
			Help:      "Total tokens read from prompt cache (0.1x cost) by model.",
		}, []string{"model"}),

		CacheSavingsTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "cache_savings_total",
			Help:      "Estimated USD saved from cache reads vs full-price input.",
		}, []string{"model"}),

		ClaudeProfileFetches: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "claude_profile_fetches_total",
			Help:      "Total Claude OAuth profile fetch attempts.",
		}, []string{"status"}),

		ClaudeProfileErrors: prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: namespace,
			Name:      "claude_profile_errors_total",
			Help:      "Total Claude OAuth profile fetch errors by error type.",
		}, []string{"error_type"}),

		ClaudeOrgTier: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "claude_org_tier",
			Help:      "Current Claude OAuth organization tier distribution (1=has tier).",
		}, []string{"org_uuid", "tier"}),

		ClaudeSubStatus: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "claude_subscription_status",
			Help:      "Current Claude OAuth subscription status (1=has status).",
		}, []string{"org_uuid", "status"}),

		ClaudeRoleCount: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: namespace,
			Name:      "claude_role_count",
			Help:      "Current Claude OAuth role distribution count.",
		}, []string{"org_uuid", "role"}),
	}

	m.QueueDepth = prometheus.NewGaugeFunc(prometheus.GaugeOpts{
		Namespace: namespace,
		Name:      "queue_depth",
		Help:      "Current depth of the AI job queue.",
	}, queueDepthFn)

	registry.MustRegister(
		m.RequestLatency,
		m.QueueDepth,
		m.ErrorRate,
		m.RateLimitHits,
		m.ActiveConnections,
		m.TokenInput,
		m.TokenOutput,
		m.UpstreamRetries,
		m.Upstream429,
		m.AdaptiveLimit,
		m.AdaptiveInFlight,
		m.CostTotal,
		m.ModelFallback,
		m.TTFB,
		m.ProfileRequests,
		m.ProfileTokenIn,
		m.ProfileTokenOut,
		m.ProfileCost,
		m.AccountTokenIn,
		m.AccountTokenOut,
		m.OptimizerCharsSaved,
		m.OptimizerRuns,
		m.ContextTruncations,
		m.TransientRetries,
		m.OptimizerDuration,
		m.OptimizerTokensSaved,
		m.ProfileOptimizerSaved,
		m.BudgetLevel,
		m.CostSavings,
		m.BillingPathRequests,
		m.BillingPathLatency,
		m.WasteFindings,
		m.WasteTokensWasted,
		m.MCPCallsTotal,
		m.MCPCallDuration,
		m.MCPCacheHits,
		m.MCPCacheMisses,
		m.MCPQuotaUsage,
		m.ImageCompressions,
		m.ImageBytesSaved,
		m.ImageBytesOriginal,
		m.VisionPreAnalysis,
		m.VisionPreAnalysisDur,
		m.CacheCreationTokens,
		m.CacheReadTokens,
		m.CacheSavingsTotal,
		m.ClaudeProfileFetches,
		m.ClaudeProfileErrors,
		m.ClaudeOrgTier,
		m.ClaudeSubStatus,
		m.ClaudeRoleCount,
	)

	return m
}

// RecordImageCompression records image compression metrics.
func (m *Metrics) RecordImageCompression(model string, originalBytes, savedBytes int, count int) {
	m.ImageCompressions.WithLabelValues(model).Add(float64(count))
	m.ImageBytesSaved.WithLabelValues(model).Add(float64(savedBytes))
	m.ImageBytesOriginal.WithLabelValues(model).Add(float64(originalBytes))
}

// RecordVisionPreAnalysis records vision pre-analysis metrics.
func (m *Metrics) RecordVisionPreAnalysis(success bool, durationSeconds float64) {
	status := "success"
	if !success {
		status = "fallback"
	}
	m.VisionPreAnalysis.WithLabelValues(status).Inc()
	m.VisionPreAnalysisDur.WithLabelValues().Observe(durationSeconds)
}

// RecordOptimization records characters saved and run count for an optimization technique.
func (m *Metrics) RecordOptimization(technique string, charsSaved int, direction string) {
	if charsSaved > 0 {
		m.OptimizerCharsSaved.WithLabelValues(technique, direction).Add(float64(charsSaved))
	}
	m.OptimizerRuns.WithLabelValues(technique).Inc()
}

// RecordOptimizationDuration records the execution time of an optimization technique.
func (m *Metrics) RecordOptimizationDuration(technique string, seconds float64) {
	m.OptimizerDuration.WithLabelValues(technique).Observe(seconds)
}

// RecordTokensSaved records total estimated tokens saved with direction label (input/output).
func (m *Metrics) RecordTokensSaved(tokens int, direction string) {
	if tokens > 0 {
		m.OptimizerTokensSaved.WithLabelValues(direction).Add(float64(tokens))
	}
}

// RecordProfileOptimization records per-profile character savings from an optimization technique.
func (m *Metrics) RecordProfileOptimization(profile, technique string, charsSaved int) {
	if charsSaved > 0 && profile != "" {
		m.ProfileOptimizerSaved.WithLabelValues(profile, technique).Add(float64(charsSaved))
	}
}

// SetBudgetLevel sets the current budget utilization level for a model.
func (m *Metrics) SetBudgetLevel(model string, level int) {
	m.BudgetLevel.WithLabelValues(model).Set(float64(level))
}

// RecordCostSavings records estimated cost savings from optimization for a model.
func (m *Metrics) RecordCostSavings(model string, usd float64) {
	if usd > 0 {
		m.CostSavings.WithLabelValues(model).Add(usd)
	}
}

// GetInputPrice returns the input price per million tokens for a model. Falls back to $3/M.
func (m *Metrics) GetInputPrice(model string) float64 {
	if p, ok := m.pricing[model]; ok {
		return p.inputPerMillion
	}
	return 3.0
}

// Handler returns an HTTP handler that serves Prometheus metrics.
func (m *Metrics) Handler() http.Handler {
	return promhttp.HandlerFor(m.registry, promhttp.HandlerOpts{
		ErrorLog: log.New(io.Discard, "", 0),
	})
}

// statusWriter wraps http.ResponseWriter to capture the actual status code.
type statusWriter struct {
	http.ResponseWriter
	status int
}

func newStatusWriter(w http.ResponseWriter) *statusWriter {
	return &statusWriter{ResponseWriter: w, status: http.StatusOK}
}

func (sw *statusWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	if h, ok := sw.ResponseWriter.(http.Hijacker); ok {
		return h.Hijack()
	}
	return nil, nil, fmt.Errorf("response writer does not implement http.Hijacker")
}

func (sw *statusWriter) WriteHeader(code int) {
	sw.status = code
	sw.ResponseWriter.WriteHeader(code)
}

// Middleware instruments every request with latency and active-connection tracking.
func (m *Metrics) Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		m.ActiveConnections.Inc()
		defer m.ActiveConnections.Dec()

		sw := newStatusWriter(w)
		start := time.Now()

		next.ServeHTTP(sw, r)

		routePattern := chi.RouteContext(r.Context()).RoutePattern()
		if routePattern == "" || routePattern == "/*" {
			// Avoid unbounded cardinality from raw URL paths.
			routePattern = "_unknown"
		}

		status := strconv.Itoa(sw.status)
		duration := time.Since(start).Seconds()
		m.RequestLatency.WithLabelValues(r.Method, routePattern, status).Observe(duration)
	})
}

// IncError increments the error counter for the given error type.
func (m *Metrics) IncError(errType string) {
	m.ErrorRate.WithLabelValues(errType).Inc()
}

// IncRateLimit increments the rate-limit counter for the given key.
// Agent-specific keys are hashed to prevent unbounded cardinality.
func (m *Metrics) IncRateLimit(key string) {
	if strings.HasPrefix(key, "agent:") {
		h := sha1.Sum([]byte(key))
		key = "agent:" + hex.EncodeToString(h[:])[:8]
	}
	m.RateLimitHits.WithLabelValues(key).Inc()
}

// RecordTokens records input and output token usage for a model and accumulates cost.
func (m *Metrics) RecordTokens(ctx context.Context, model string, input, output int) {
	m.TokenInput.WithLabelValues(model).Add(float64(input))
	m.TokenOutput.WithLabelValues(model).Add(float64(output))
	var inputCost, outputCost float64
	var cost float64
	if p, ok := m.pricing[model]; ok {
		inputCost = float64(input) / 1_000_000 * p.inputPerMillion
		outputCost = float64(output) / 1_000_000 * p.outputPerMillion
		cost = inputCost + outputCost
		if inputCost > 0 {
			m.CostTotal.WithLabelValues(model, "input").Add(inputCost)
		}
		if outputCost > 0 {
			m.CostTotal.WithLabelValues(model, "output").Add(outputCost)
		}
	}
	if m.usageRecorder != nil && (input > 0 || output > 0) {
		m.usageRecorder(ctx, model, input, output, cost)
	}
}

// RecordCacheUsage records prompt cache token breakdown and estimated savings.
func (m *Metrics) RecordCacheUsage(model string, creation, read int) {
	if creation > 0 {
		m.CacheCreationTokens.WithLabelValues(model).Add(float64(creation))
	}
	if read > 0 {
		m.CacheReadTokens.WithLabelValues(model).Add(float64(read))
		if p, ok := m.pricing[model]; ok {
			savings := float64(read) / 1_000_000 * p.inputPerMillion * 0.9
			m.CacheSavingsTotal.WithLabelValues(model).Add(savings)
		}
	}
}

// RecordClaudeProfileFetch records a Claude OAuth profile fetch attempt.
func (m *Metrics) RecordClaudeProfileFetch(success bool) {
	status := "success"
	if !success {
		status = "error"
	}
	m.ClaudeProfileFetches.WithLabelValues(status).Inc()
}

// RecordClaudeProfileError records a Claude OAuth profile fetch error.
func (m *Metrics) RecordClaudeProfileError(errorType string) {
	m.ClaudeProfileErrors.WithLabelValues(errorType).Inc()
}

// SetClaudeOrgTier records the organization tier for a Claude OAuth account.
func (m *Metrics) SetClaudeOrgTier(orgUUID, tier string) {
	m.ClaudeOrgTier.WithLabelValues(orgUUID, tier).Set(1)
}

// SetClaudeSubStatus records the subscription status for a Claude OAuth organization.
func (m *Metrics) SetClaudeSubStatus(orgUUID, status string) {
	m.ClaudeSubStatus.WithLabelValues(orgUUID, status).Set(1)
}

// SetClaudeRole records the role count for a Claude OAuth organization.
func (m *Metrics) SetClaudeRole(orgUUID, role string) {
	m.ClaudeRoleCount.WithLabelValues(orgUUID, role).Inc()
}

// SetUsageRecorder registers a callback invoked after every RecordTokens call.
func (m *Metrics) SetUsageRecorder(fn func(ctx context.Context, model string, input, output int, cost float64)) {
	m.usageRecorder = fn
}

// RecordProfileUsage records per-profile token usage and cost.
func (m *Metrics) RecordProfileUsage(profile, model string, input, output int, cost float64) {
	m.ProfileRequests.WithLabelValues(profile, model).Inc()
	if input > 0 {
		m.ProfileTokenIn.WithLabelValues(profile, model).Add(float64(input))
	}
	if output > 0 {
		m.ProfileTokenOut.WithLabelValues(profile, model).Add(float64(output))
	}
	if cost > 0 {
		if p, ok := m.pricing[model]; ok {
			ic := float64(input) / 1_000_000 * p.inputPerMillion
			oc := float64(output) / 1_000_000 * p.outputPerMillion
			if ic > 0 {
				m.ProfileCost.WithLabelValues(profile, model, "input").Add(ic)
			}
			if oc > 0 {
				m.ProfileCost.WithLabelValues(profile, model, "output").Add(oc)
			}
		}
	}
}

// IncRetry increments the upstream retry counter.
// RecordAccountUsage records per-account token usage in Prometheus.
func (m *Metrics) RecordAccountUsage(accountID, model string, input, output int) {
	if input > 0 {
		m.AccountTokenIn.WithLabelValues(accountID, model).Add(float64(input))
	}
	if output > 0 {
		m.AccountTokenOut.WithLabelValues(accountID, model).Add(float64(output))
	}
}

func (m *Metrics) IncRetry() {
	m.UpstreamRetries.Inc()
}

// Inc429 increments the upstream 429 counter.
func (m *Metrics) Inc429() {
	m.Upstream429.Inc()
}

// IncContextTruncation increments the auto-truncation counter for a model.
func (m *Metrics) IncContextTruncation(model string) {
	m.ContextTruncations.WithLabelValues(model).Inc()
}

// IncTransientRetry increments the transient retry counter for a status code and model.
func (m *Metrics) IncTransientRetry(statusCode int, model string) {
	m.TransientRetries.WithLabelValues(strconv.Itoa(statusCode), model).Inc()
}

// RecordBillingPath records a billing path routing event (go_direct, sidecar, direct, billing_rejected).
func (m *Metrics) RecordBillingPath(path, model, profile string) {
	m.BillingPathRequests.WithLabelValues(path, model, profile).Inc()
}

// RecordBillingPathLatency records the total latency for a billing path request.
func (m *Metrics) RecordBillingPathLatency(path, model string, seconds float64) {
	m.BillingPathLatency.WithLabelValues(path, model).Observe(seconds)
}

// RecordFallback records a model fallback event.
func (m *Metrics) RecordFallback(requested, selected string) {
	m.ModelFallback.WithLabelValues(requested, selected).Inc()
}

// RecordTTFB records time-to-first-byte for a streaming response.
func (m *Metrics) RecordTTFB(model string, d time.Duration) {
	m.TTFB.WithLabelValues(model).Observe(d.Seconds())
}

// ModelStatusSnapshot holds per-model limiter state for metrics export.
type ModelStatusSnapshot struct {
	Name     string
	Limit    float64
	InFlight float64
}

// Registry returns the underlying Prometheus registry for external metric registration.
func (m *Metrics) Registry() *prometheus.Registry {
	return m.registry
}

// UpdateAdaptiveMetrics sets the adaptive limit and in-flight gauges from a limiter snapshot.
func (m *Metrics) UpdateAdaptiveMetrics(statuses []ModelStatusSnapshot) {
	for _, s := range statuses {
		m.AdaptiveLimit.WithLabelValues(s.Name).Set(s.Limit)
		m.AdaptiveInFlight.WithLabelValues(s.Name).Set(s.InFlight)
	}
}

// IncWasteFinding increments waste findings counter.
func (m *Metrics) IncWasteFinding(detector, severity string) {
	m.WasteFindings.WithLabelValues(detector, severity).Inc()
}

// RecordWasteTokens records tokens identified as wasted by a detector.
func (m *Metrics) RecordWasteTokens(detector string, tokens int) {
	m.WasteTokensWasted.WithLabelValues(detector).Add(float64(tokens))
}

// SeedMockData populates all optimizer/waste/budget metrics with initial sample data
// so that stat/barchart panels display immediately. Timeseries panels using rate()
// are fed by StartMockDataLoop.
func (m *Metrics) SeedMockData() {
	m.SeedMockCategory("all")
}

func (m *Metrics) SeedMockCategory(category string) {
	if category == "all" || category == "optimizer" {
		m.seedOptimizers()
	}
	if category == "all" || category == "waste" {
		m.seedWaste()
	}
	if category == "all" || category == "budget" {
		m.seedBudget()
	}
	if category == "all" || category == "billing" {
		m.seedBilling()
	}
}

func (m *Metrics) seedOptimizers() {
	techniques := []struct {
		name       string
		charsSaved float64
		runs       int
		duration   float64
	}{
		{"chunker", 128000, 320, 0.012},
		{"delta", 86400, 210, 0.008},
		{"sketch_dedup", 42000, 180, 0.005},
		{"semantic_dedup", 31200, 95, 0.025},
		{"disclosure", 0, 450, 0.003},
		{"packer", 15600, 120, 0.015},
		{"bandit", 0, 780, 0.042},
		{"prefetcher", 0, 640, 0.006},
		{"summarizer", 96000, 160, 0.085},
		{"warmstart", 0, 520, 0.018},
		{"caveman", 54000, 88, 0.035},
	}
	for _, t := range techniques {
		m.OptimizerCharsSaved.WithLabelValues(t.name, "input").Add(t.charsSaved)
		for i := 0; i < t.runs; i++ {
			m.OptimizerRuns.WithLabelValues(t.name).Inc()
		}
		m.OptimizerDuration.WithLabelValues(t.name).Observe(t.duration)
		m.OptimizerDuration.WithLabelValues(t.name).Observe(t.duration * 0.7)
		m.OptimizerDuration.WithLabelValues(t.name).Observe(t.duration * 1.4)
	}
	m.OptimizerTokensSaved.WithLabelValues("input").Add(42800)
	m.CostSavings.WithLabelValues("claude-sonnet-4-6").Add(3.47)
}

func (m *Metrics) seedBudget() {
	models := []struct {
		name  string
		level float64
	}{
		{"glm-5.1", 0},
		{"glm-5-turbo", 0},
		{"glm-5", 1},
		{"glm-4.7", 0},
		{"glm-4.6", 2},
		{"glm-4.5", 0},
	}
	for _, md := range models {
		m.BudgetLevel.WithLabelValues(md.name).Set(md.level)
	}
}

func (m *Metrics) seedWaste() {
	detectors := []struct {
		name     string
		findings int
		tokens   float64
	}{
		{"repetition", 120, 8400},
		{"padding", 85, 5600},
		{"off_topic", 42, 3200},
		{"redundancy", 67, 4100},
	}
	severities := []string{"low", "medium", "high"}
	for _, d := range detectors {
		for i, sev := range severities {
			count := d.findings / (i + 1)
			for j := 0; j < count; j++ {
				m.WasteFindings.WithLabelValues(d.name, sev).Inc()
			}
		}
		m.WasteTokensWasted.WithLabelValues(d.name).Add(d.tokens)
	}
}

func (m *Metrics) seedBilling() {
	paths := []struct {
		path    string
		model   string
		profile string
		count   int
		latency float64
	}{
		{"go_direct", "claude-sonnet-4-6", "default", 180, 1.2},
		{"go_direct", "claude-haiku-4-5-20251001", "default", 95, 0.6},
		{"sidecar", "claude-sonnet-4-6", "default", 12, 2.8},
		{"direct", "claude-sonnet-4-6", "default", 5, 1.5},
		{"billing_rejected", "claude-sonnet-4-6", "default", 3, 0.3},
		{"zai_proxy", "glm-5.1", "default", 240, 3.5},
		{"zai_proxy", "glm-4.6", "default", 160, 2.1},
		{"zai_vision", "glm-4.6v", "default", 30, 5.2},
		{"openai_proxy", "gpt-4o", "default", 45, 1.8},
	}
	for _, p := range paths {
		for i := 0; i < p.count; i++ {
			m.BillingPathRequests.WithLabelValues(p.path, p.model, p.profile).Inc()
		}
		m.BillingPathLatency.WithLabelValues(p.path, p.model).Observe(p.latency)
		m.BillingPathLatency.WithLabelValues(p.path, p.model).Observe(p.latency * 0.7)
		m.BillingPathLatency.WithLabelValues(p.path, p.model).Observe(p.latency * 1.4)
	}

	profiles := []struct {
		profile string
		model   string
		input   int
		output  int
	}{
		{"default", "claude-sonnet-4-6", 85000, 12000},
		{"default", "glm-5.1", 62000, 8500},
		{"production", "claude-sonnet-4-6", 45000, 6000},
		{"staging", "glm-4.6", 12000, 2000},
	}
	for _, p := range profiles {
		m.ProfileRequests.WithLabelValues(p.profile, p.model).Add(float64(p.input + p.output))
		m.ProfileTokenIn.WithLabelValues(p.profile, p.model).Add(float64(p.input))
		m.ProfileTokenOut.WithLabelValues(p.profile, p.model).Add(float64(p.output))
		m.ProfileCost.WithLabelValues(p.profile, p.model, "input").Add(float64(p.input) / 1_000_000 * 3.0)
		m.ProfileCost.WithLabelValues(p.profile, p.model, "output").Add(float64(p.output) / 1_000_000 * 15.0)
	}

}

// StartMockDataLoop continuously increments mock metrics so that rate()-based
// Grafana timeseries panels show live data. Stops when ctx is cancelled.
func (m *Metrics) StartMockDataLoop(ctx context.Context) {
	go func() {
		ticker := time.NewTicker(5 * time.Second)
		defer ticker.Stop()

		techniques := []struct {
			name     string
			charsInc float64
			runsInc  int
			duration float64
		}{
			{"chunker", 120, 1, 0.012},
			{"delta", 80, 1, 0.008},
			{"sketch_dedup", 40, 1, 0.005},
			{"semantic_dedup", 30, 1, 0.025},
			{"disclosure", 0, 2, 0.003},
			{"packer", 15, 1, 0.015},
			{"bandit", 0, 3, 0.042},
			{"prefetcher", 0, 2, 0.006},
			{"summarizer", 90, 1, 0.085},
			{"warmstart", 0, 2, 0.018},
			{"caveman", 50, 1, 0.035},
		}

		wasteDetectors := []struct {
			name     string
			findings int
			tokens   float64
		}{
			{"repetition", 2, 80},
			{"padding", 1, 50},
			{"off_topic", 1, 30},
			{"redundancy", 1, 40},
		}

		for {
			select {
			case <-ctx.Done():
				return
			case <-ticker.C:
				for _, t := range techniques {
					if t.charsInc > 0 {
						m.OptimizerCharsSaved.WithLabelValues(t.name, "input").Add(t.charsInc)
					}
					for i := 0; i < t.runsInc; i++ {
						m.OptimizerRuns.WithLabelValues(t.name).Inc()
					}
					m.OptimizerDuration.WithLabelValues(t.name).Observe(t.duration)
				}

				m.OptimizerTokensSaved.WithLabelValues("input").Add(40)
				m.CostSavings.WithLabelValues("claude-sonnet-4-6").Add(0.003)

				severities := []string{"low", "medium", "high"}
				for _, d := range wasteDetectors {
					for _, sev := range severities {
						for j := 0; j < d.findings; j++ {
							m.WasteFindings.WithLabelValues(d.name, sev).Inc()
						}
					}
					m.WasteTokensWasted.WithLabelValues(d.name).Add(d.tokens)
				}
			}

			// Billing/profile continuous data
			billingTickPaths := []struct {
				path    string
				model   string
				profile string
				latency float64
			}{
				{"go_direct", "claude-sonnet-4-6", "default", 1.1},
				{"zai_proxy", "glm-5.1", "default", 3.2},
				{"openai_proxy", "gpt-4o", "default", 1.7},
			}
			for _, bp := range billingTickPaths {
				m.BillingPathRequests.WithLabelValues(bp.path, bp.model, bp.profile).Inc()
				m.BillingPathLatency.WithLabelValues(bp.path, bp.model).Observe(bp.latency)
			}
			m.ProfileRequests.WithLabelValues("default", "claude-sonnet-4-6").Add(2)
			m.ProfileTokenIn.WithLabelValues("default", "claude-sonnet-4-6").Add(120)
			m.ProfileTokenOut.WithLabelValues("default", "claude-sonnet-4-6").Add(30)
			m.ProfileCost.WithLabelValues("default", "claude-sonnet-4-6", "input").Add(0.00036)
			m.ProfileCost.WithLabelValues("default", "claude-sonnet-4-6", "output").Add(0.00045)
		}
	}()
}

// mockLoopState tracks the running mock data loop.
type mockLoopState struct {
	mu      sync.Mutex
	cancel  context.CancelFunc
	running bool
}

var mockLoop mockLoopState

// StartMockLoop starts the continuous mock data loop. Returns false if already running.
func (m *Metrics) StartMockLoop() bool {
	mockLoop.mu.Lock()
	defer mockLoop.mu.Unlock()
	if mockLoop.running {
		return false
	}
	ctx, cancel := context.WithCancel(context.Background())
	mockLoop.cancel = cancel
	mockLoop.running = true
	m.StartMockDataLoop(ctx)
	return true
}

// StopMockLoop stops the continuous mock data loop. Returns false if not running.
func (m *Metrics) StopMockLoop() bool {
	mockLoop.mu.Lock()
	defer mockLoop.mu.Unlock()
	if !mockLoop.running {
		return false
	}
	mockLoop.cancel()
	mockLoop.running = false
	return true
}

// MockLoopRunning returns whether the mock data loop is active.
func (m *Metrics) MockLoopRunning() bool {
	mockLoop.mu.Lock()
	defer mockLoop.mu.Unlock()
	return mockLoop.running
}
